#!/bin/bash
#
# deploy.sh
# ---------
# Purpose:      Ship the built payload to the EC2 host and restart the service.
#               Builds locally and copies artifacts: the production instance is
#               a small box, and building there competes with the running app
#               for memory.
#
# Usage:        ./scripts/deploy.sh [--dry-run] [--skip-preflight] [-h|--help]
#
# Arguments:
#   --dry-run          Show what rsync would transfer; make no remote changes.
#   --skip-preflight   Skip the local build/verify step (payload must exist).
#
# Prerequisites:
#   - DEPLOY_HOST set (e.g. ubuntu@ec2-1-2-3-4.compute-1.amazonaws.com).
#   - SSH access to that host, with sudo for the service restart.
#   - Host already provisioned: see shell_scripts/01..04.
#   - rsync, ssh, curl on PATH.
#
# What it does:
#   1. Runs scripts/deploy-preflight.sh (unless --skip-preflight).
#   2. Rsyncs dist/ to $DEPLOY_DIR/dist (with --delete: dist is fully generated).
#   3. Rsyncs package.json and package-lock.json (no --delete).
#   4. Runs the remote redeploy: npm ci --omit=dev, restart, health check.
#
# The remote .env is never transferred and never deleted — production secrets
# live only on the host (shell_scripts/02_create_env.sh) and survive deploys.
#
# Environment variables:
#   DEPLOY_HOST      Required. user@host for ssh/rsync.
#   DEPLOY_DIR       Remote app directory. Default: /var/www/portal_brasileirao
#   DEPLOY_SERVICE   systemd unit name. Default: portal-brasileirao
#   DEPLOY_SSH_KEY   Optional path to an SSH private key.
#   HEALTH_URL       Post-deploy health URL. Default: http://127.0.0.1:3000/api/health
#                    (checked over SSH, from the host's own loopback)
#
# Exit codes:
#   0  Deployed and health-checked.
#   1  Any step failed.

set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DEPLOY_HOST="${DEPLOY_HOST:-}"
DEPLOY_DIR="${DEPLOY_DIR:-/var/www/portal_brasileirao}"
DEPLOY_SERVICE="${DEPLOY_SERVICE:-portal-brasileirao}"
DEPLOY_SSH_KEY="${DEPLOY_SSH_KEY:-}"
HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:3000/api/health}"

DRY_RUN=0
SKIP_PREFLIGHT=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        --skip-preflight) SKIP_PREFLIGHT=1 ;;
        *) echo "Unknown argument: $arg (try --help)" >&2; exit 1 ;;
    esac
done

if [[ -z "$DEPLOY_HOST" ]]; then
    echo "Error: DEPLOY_HOST is not set (e.g. ubuntu@1.2.3.4). See --help." >&2
    exit 1
fi

SSH_OPTS=()
RSYNC_SSH="ssh"
if [[ -n "$DEPLOY_SSH_KEY" ]]; then
    if [[ ! -f "$DEPLOY_SSH_KEY" ]]; then
        echo "Error: DEPLOY_SSH_KEY not found: $DEPLOY_SSH_KEY" >&2
        exit 1
    fi
    SSH_OPTS=(-i "$DEPLOY_SSH_KEY")
    RSYNC_SSH="ssh -i $DEPLOY_SSH_KEY"
fi

cd "$PROJECT_ROOT"

if [[ "$SKIP_PREFLIGHT" -eq 0 ]]; then
    "$SCRIPT_DIR/deploy-preflight.sh"
else
    echo "==> Skipping preflight (--skip-preflight)"
    if [[ ! -f dist/server.cjs ]]; then
        echo "Error: dist/server.cjs missing; cannot skip preflight." >&2
        exit 1
    fi
fi

RSYNC_FLAGS=(-az --human-readable)
if [[ "$DRY_RUN" -eq 1 ]]; then
    RSYNC_FLAGS+=(--dry-run --itemize-changes)
    echo ""
    echo "==> DRY RUN — no remote changes will be made"
fi

echo ""
echo "==> Syncing dist/ to ${DEPLOY_HOST}:${DEPLOY_DIR}/dist"
# --delete is safe here and only here: dist/ is fully regenerated by the build,
# so stale assets from an older bundle should not linger.
rsync "${RSYNC_FLAGS[@]}" --delete -e "$RSYNC_SSH" \
    dist/ "${DEPLOY_HOST}:${DEPLOY_DIR}/dist/"

echo "==> Syncing package manifests"
# No --delete: this targets the app root, which also holds .env and node_modules.
rsync "${RSYNC_FLAGS[@]}" -e "$RSYNC_SSH" \
    package.json package-lock.json "${DEPLOY_HOST}:${DEPLOY_DIR}/"

if [[ "$DRY_RUN" -eq 1 ]]; then
    echo ""
    echo "Dry run complete — nothing was changed on ${DEPLOY_HOST}."
    exit 0
fi

echo ""
echo "==> Installing production dependencies and restarting ${DEPLOY_SERVICE}"
ssh "${SSH_OPTS[@]}" "$DEPLOY_HOST" bash -s -- \
    "$DEPLOY_DIR" "$DEPLOY_SERVICE" "$HEALTH_URL" <<'REMOTE'
set -euo pipefail
DEPLOY_DIR="$1"
DEPLOY_SERVICE="$2"
HEALTH_URL="$3"

cd "$DEPLOY_DIR"

if [[ ! -f .env ]]; then
    echo "Error: $DEPLOY_DIR/.env missing. Run shell_scripts/02_create_env.sh first." >&2
    exit 1
fi

echo "--> npm ci --omit=dev"
npm ci --omit=dev --no-audit --no-fund

echo "--> restarting ${DEPLOY_SERVICE}"
sudo systemctl restart "$DEPLOY_SERVICE"

echo "--> waiting for health"
for _ in $(seq 1 30); do
    if curl -sf "$HEALTH_URL" | grep -q '"status":"ok"'; then
        echo "--> healthy: $(curl -sf "$HEALTH_URL")"
        exit 0
    fi
    sleep 1
done

echo "Error: ${DEPLOY_SERVICE} did not become healthy." >&2
echo "Recent logs:" >&2
sudo journalctl -u "$DEPLOY_SERVICE" -n 40 --no-pager >&2
exit 1
REMOTE

echo ""
echo "Deployed to ${DEPLOY_HOST}."
