/**
 * Renders `src/data/escalacoes.ts`. Imported by `scripts/sync-goals.ts`, which
 * is the only thing that writes it.
 *
 * **It is a module rather than a heredoc inside the sync for one reason: the
 * committed file has to be byte-identical to what the next sync would write.**
 * The tuple encoding landed by re-rendering the data already on disk rather
 * than by re-fetching 252 matches from a host that throttles at the socket, and
 * a second copy of this formatting — even one that looked right — would have
 * left the next real sync rewriting all 258 lines with a diff nobody could read
 * and no way to tell a formatting change from a data change.
 *
 * The encoding itself is `encodeLineups` in `escalacao-core.ts`, beside the
 * decoder that reads it back; this file only decides where the newlines go.
 */
import { encodeLineups } from "@/escalacao-core";
import type { Lineup } from "@/src/types";

const j = JSON.stringify;

/**
 * One fixture per line.
 *
 * Not prettier than that, and deliberately: 252 lines of tuples is a file
 * `git diff` can report a changed *fixture* in, where one row per player put
 * 18 016 lines in front of a reader looking for the one that moved. It is the
 * shape `club-scouts-history.ts` already takes, for the same reason.
 */
const renderLineups = (lineups: Lineup[]): string =>
  encodeLineups(lineups)
    .map(
      ([clubCode, players, subs]) =>
        `[${j(clubCode)},[` +
        players.map((p) => `[${p.map((field) => j(field)).join(",")}]`).join(",") +
        `]` +
        (subs ? `,[` + subs.map((s) => `[${s.map((field) => j(field)).join(",")}]`).join(",") + `]` : "") +
        `]`,
    )
    .join(",");

export const renderEscalacoesFile = (
  escalacoes: Record<string, Lineup[]>,
  generatedOn: string,
): string => {
  const ids = Object.keys(escalacoes).sort((a, b) => Number(a) - Number(b));
  return `import { decodeLineups } from "@/escalacao-core";
import type { Lineup, LineupEntry } from "@/src/types";

/**
 * GENERATED by scripts/sync-goals.ts — the same run that writes goals.ts.
 *
 * **One script, because the escalação is in the payload the goals already
 * arrive in.** A second sync would have walked the same listing, resolved the
 * same join and re-fetched every match — doubling the traffic against a host
 * that throttles at the socket with no 429 to warn you.
 *
 * Who started and who was on the bench, keyed by **our** match id. Every entry
 * carries two complete sheets of eleven starters; \`lineupsReconcile\` refuses
 * anything less, so an absent match means "not synced or not published", never
 * "no lineup".
 *
 * **Stored as tuples, one fixture per line, and read back through
 * \`decodeLineups\`.** \`LineupEntry\` in \`src/types.ts\` carries the encoding and
 * the measurements that chose it; the short version is that this file was
 * 791.7 KB as objects and is 318.3 KB as tuples, and that converting it to JSON
 * instead would have saved half as much while giving up the typecheck. Those two
 * figures are a reading taken when the encoding landed, over 252 fixtures — the
 * file grows, so measure it rather than quoting them.
 *
 * **Nothing outside this file sees a tuple.** \`ESCALACOES\` is \`Lineup[]\` exactly
 * as it always was, which is why no component, no core module and no test
 * changed when the encoding did.
 *
 * Generated ${generatedOn}.
 */
const ENTRIES: Record<string, LineupEntry[]> = {
${ids.map((id) => `  ${j(id)}: [${renderLineups(escalacoes[id])}],`).join("\n")}
};

/**
 * Decoded once at import, for every fixture the file holds.
 *
 * Eager rather than per-lookup because \`withLineups\` attaches the whole season
 * to \`/api/matches\` anyway, so a lazy decode would buy nothing and would owe a
 * cache. **8 ms for the whole file**, measured over 252 fixtures when this
 * landed — once, at import, against a server that then answers from a 60s
 * cache.
 */
export const ESCALACOES: Record<string, Lineup[]> = Object.fromEntries(
  Object.entries(ENTRIES).map(([id, entries]) => [id, decodeLineups(entries)]),
);
`;
};
