/**
 * Generates the Material Design 3 colour tokens in `src/index.css`.
 *
 * Rewrites only the region between the MD3-TOKENS markers, so the prose and the
 * `body` rule around it stay hand-editable. Re-running is deterministic: same
 * seed in, same hexes out.
 *
 * Run: `npx tsx scripts/generate-md3-tokens.ts`
 *      `npx tsx scripts/generate-md3-tokens.ts --check`  (CI / pre-commit)
 *
 * The `--check` mode regenerates into memory and diffs against the file, so a
 * hand-edited hex is caught rather than silently overwritten on the next run.
 *
 * See `docs/roadmap.md` phase M1. This script is the derivation *and* the
 * contrast gate: it refuses to emit a palette whose text pairings fall below
 * WCAG AA, because "contrast is measured, not eyeballed" is a constraint the
 * roadmap records and a redesign is exactly how it gets lost.
 */
import { readFileSync, writeFileSync } from "node:fs";

import { contrastRatio, hctFromHex, tonalPalette } from "@/md3-color-core";

const CSS_PATH = new URL("../src/index.css", import.meta.url).pathname;
const START = "/* MD3-TOKENS:START — generated by scripts/generate-md3-tokens.ts */";
const END = "/* MD3-TOKENS:END */";

// ---------------------------------------------------------------- the seed

/**
 * The seed. Chosen as the app's existing accent so the migration re-derives the
 * palette the reader already knows rather than rebranding underneath them.
 */
const SEED = "#10b981";

/**
 * MD3 derives every palette from the seed hue, including the neutrals. Here
 * that would tint every surface green, which is a *larger* change than the one
 * being asked for — the app's surfaces are slate today and the seed is an
 * emerald 90 degrees away. So the neutral hue is pinned to the existing slate
 * and only the accent palettes follow the seed. Material's own `DynamicScheme`
 * takes explicit neutral palettes for exactly this reason; it is a supported
 * configuration, not a departure from the system.
 *
 * Raise `NEUTRAL_CHROMA` toward 12 to bring back more of slate's blue cast;
 * MD3's own value is 6, and the surfaces read greyer at it than they do today.
 */
const NEUTRAL_HUE = 258;
const NEUTRAL_CHROMA = 6;
const NEUTRAL_VARIANT_CHROMA = 8;

const seed = hctFromHex(SEED);

const primary = tonalPalette(seed.hue, 48);
const secondary = tonalPalette(seed.hue, 16);
const tertiary = tonalPalette(seed.hue + 60, 24);
const neutral = tonalPalette(NEUTRAL_HUE, NEUTRAL_CHROMA);
const neutralVariant = tonalPalette(NEUTRAL_HUE, NEUTRAL_VARIANT_CHROMA);
/** MD3's fixed error palette — the one part of the system that ignores the seed. */
const error = tonalPalette(25, 84);
/**
 * `warning` has no MD3 role. MD3 handles this as an "extended colour": a colour
 * outside the scheme gets its own tonal palette and the same tone assignments,
 * so it behaves like a role even though the spec does not name it. Seeded from
 * the amber shipping today so the meaning survives the migration.
 */
const warning = (() => {
  const amber = hctFromHex("#f59e0b");
  return tonalPalette(amber.hue, amber.chroma);
})();

// ------------------------------------------------------------- tone mapping

interface Tokens {
  [name: string]: string;
}

/**
 * Tokens that are deliberately identical in both themes, and must not be swept
 * into the tonal system.
 *
 * `scrim` is MD3's own (neutral tone 0) and was already black here. The `plate`
 * trio is ours: broadcaster marks are dark artwork on transparent grounds, so
 * they need a light backing in *both* themes or they vanish on a dark page.
 * Deriving these from a palette is the obvious-looking change that breaks them.
 */
const THEME_INVARIANT: Tokens = {
  scrim: "#000000",
  plate: "#ffffff",
  "plate-line": "#d8dee7",
  "plate-ink": "#0f172a",
};

const roleTokens = (mode: "dark" | "light"): Tokens => {
  const dark = mode === "dark";
  const t = <T>(darkValue: T, lightValue: T): T => (dark ? darkValue : lightValue);

  return {
    // ---- MD3 accent roles
    primary: primary(t(80, 40)),
    "on-primary": primary(t(20, 100)),
    "primary-container": primary(t(30, 90)),
    "on-primary-container": primary(t(90, 10)),

    secondary: secondary(t(80, 40)),
    "on-secondary": secondary(t(20, 100)),
    "secondary-container": secondary(t(30, 90)),
    "on-secondary-container": secondary(t(90, 10)),

    tertiary: tertiary(t(80, 40)),
    "on-tertiary": tertiary(t(20, 100)),
    "tertiary-container": tertiary(t(30, 90)),
    "on-tertiary-container": tertiary(t(90, 10)),

    error: error(t(80, 40)),
    "on-error": error(t(20, 100)),
    "error-container": error(t(30, 90)),
    "on-error-container": error(t(90, 10)),

    // ---- MD3 surface roles. The container ladder replaces shadow-based
    // elevation: a "higher" surface is a lighter tone, which is what keeps a
    // dark theme legible where drop shadows cannot be seen at all.
    surface: neutral(t(6, 98)),
    "surface-container-lowest": neutral(t(4, 100)),
    "surface-container-low": neutral(t(10, 96)),
    "surface-container": neutral(t(12, 94)),
    "surface-container-high": neutral(t(17, 92)),
    "surface-container-highest": neutral(t(22, 90)),
    "on-surface": neutral(t(90, 10)),
    "on-surface-variant": neutralVariant(t(80, 30)),

    outline: neutralVariant(t(60, 50)),
    "outline-variant": neutralVariant(t(30, 80)),

    "inverse-surface": neutral(t(90, 20)),
    "inverse-on-surface": neutral(t(20, 95)),
    "inverse-primary": primary(t(40, 80)),
  };
};

/**
 * The app's **extensions** to MD3's colour system.
 *
 * Not aliases any more, which is what M6 changed: the seven names that were
 * exactly a role are gone, and their call sites spell the role. What is left is
 * what MD3 has no room for — a surface gets two inks and a standings table
 * needs five, and the status fills have no counterpart at all because MD3
 * carries `error` and nothing else of the kind.
 *
 * M1 changes values, not call sites: keeping these aliases for one phase means
 * a visual regression has exactly one possible cause. `docs/roadmap.md` records
 * the mapping; the odd one out is `surface`, which in MD3 means the *page* but
 * here still means a card. That rename lands in M2 along with the component
 * edits, rather than being smuggled into the phase that changes every colour.
 */
const extensionTokens = (mode: "dark" | "light"): Tokens => {
  const dark = mode === "dark";
  const t = <T>(darkValue: T, lightValue: T): T => (dark ? darkValue : lightValue);

  return {
    // The surface ladder went first, in M2. The seven aliases that were exactly
    // an MD3 role — `ink`, `ink-soft`, `ink-inverted`, `line`, `line-strong`,
    // `positive-ink`, `negative-ink` — went in M6, and their 51 call sites now
    // name the role. What is left is genuinely an **extension**: MD3 gives a
    // surface two inks and a standings table needs five, and the status fills
    // have no role at all because MD3's colour system carries `error` and
    // nothing else of the kind.
    //
    // Nothing here may duplicate a role again. `assertNoRoleDuplicates` below
    // refuses to emit a palette where one does, in either theme — two names for
    // one colour is the state M2 deferred and M6 spent 51 call sites clearing.
    "ink-muted": neutralVariant(t(70, 40)),
    // Light's faint tones run darker than the dark theme's run light. The
    // backgrounds are not mirror images — `surface-container` sits at tone 94 on
    // light but tone 12 on dark, so the light theme has much less room beneath
    // it before AA fails. Tone 50 here measured 3.86:1 against it; 45 clears it.
    "ink-faint": neutralVariant(t(60, 45)),
    "ink-ghost": neutralVariant(t(50, 55)),

    positive: primary(t(70, 60)),
    negative: error(t(60, 50)),
    warning: warning(t(70, 70)),
    "warning-ink": warning(t(85, 40)),
  };
};

// ----------------------------------------------------------- contrast gate

interface Pairing {
  label: string;
  fg: string;
  bg: string;
  floor: number;
  /** False when no component paints this combination today — see `backgroundsFor`. */
  live: boolean;
}

/**
 * The backgrounds text is actually painted on.
 *
 * Every entry here is a solid token as of M2. Before it, a filled `Surface` was
 * `bg-surface/50`, so the colour behind a card's text was a composite that no
 * token held — and this gate originally measured the solid token instead, which
 * flattered the light theme. Going solid honours MD3's elevation model, since
 * the tone already encodes the elevation, and removes the composite from this
 * list. `blend` stays in `md3-color-core.ts` for the next translucent fill,
 * because that mistake is an easy one to make twice.
 *
 * `live: false` marks a combination no component currently paints. Those are
 * still checked — a latent pairing below AA is a trap that springs the first
 * time someone reaches for it — but a phase spending its scarcest headroom
 * should know it is protecting something nobody renders yet.
 */
const backgroundsFor = (
  tokens: Tokens,
): { name: string; hex: string; live: (fg: string) => boolean }[] => [
  { name: "surface (the page)", hex: tokens.surface, live: () => true },
  {
    name: "surface-container-low (a card)",
    hex: tokens["surface-container-low"],
    live: () => true,
  },
  {
    name: "surface-container",
    hex: tokens["surface-container"],
    // Every call site — the status badges in MatchList and MatchPage, and the
    // Button and NavBar state layers — pairs with `on-surface-variant` or
    // `ink-muted`. Nothing paints the fainter inks on it, and nothing paints
    // `primary` as text on it: the stat tiles that do sit on a card.
    live: (fg) =>
      fg === "on-surface" || fg === "on-surface-variant" || fg === "ink-muted",
  },
];

const pairingsFor = (mode: string, tokens: Tokens): Pairing[] => {
  const backgrounds = backgroundsFor(tokens);
  const text = [
    "on-surface",
    "on-surface-variant",
    "ink-muted",
    "ink-faint",
    "primary",
    "error",
    "warning-ink",
  ];

  const pairings: Pairing[] = [];
  for (const fg of text) {
    for (const bg of backgrounds) {
      pairings.push({
        label: `${mode}: ${fg} on ${bg.name}`,
        fg: tokens[fg],
        bg: bg.hex,
        floor: 4.5,
        live: bg.live(fg),
      });
    }
  }

  // Non-text: `ink-ghost` backs underline decoration and the large score
  // separator, so the 3:1 floor applies rather than AA.
  for (const bg of backgrounds) {
    pairings.push({
      label: `${mode}: ink-ghost on ${bg.name} (non-text)`,
      fg: tokens["ink-ghost"],
      bg: bg.hex,
      floor: 3,
      live: bg.live("ink-ghost"),
    });
  }

  // The current nav entry is a filled chip: `on-surface` background with
  // `inverse-on-surface` text. Both were spelled `ink`/`ink-inverted` until M6.
  pairings.push({
    label: `${mode}: inverse-on-surface on on-surface (nav chip)`,
    fg: tokens["inverse-on-surface"],
    bg: tokens["on-surface"],
    floor: 4.5,
    live: true,
  });
  pairings.push({
    label: `${mode}: plate-ink on plate`,
    fg: tokens["plate-ink"],
    bg: tokens.plate,
    floor: 4.5,
    live: true,
  });

  // MD3's own promise: every `on-` role is readable on its pair. No component
  // names these yet — the roles ship in M1 and the call sites arrive in M2 — but
  // the guarantee is the reason to adopt the system, so it is checked from now.
  for (const role of ["primary", "secondary", "tertiary", "error"]) {
    pairings.push({
      label: `${mode}: on-${role} on ${role}`,
      fg: tokens[`on-${role}`],
      bg: tokens[role],
      floor: 4.5,
      live: false,
    });
    pairings.push({
      label: `${mode}: on-${role}-container on ${role}-container`,
      fg: tokens[`on-${role}-container`],
      bg: tokens[`${role}-container`],
      floor: 4.5,
      live: false,
    });
  }
  pairings.push({
    label: `${mode}: on-surface-variant on surface`,
    fg: tokens["on-surface-variant"],
    bg: tokens.surface,
    floor: 4.5,
    live: false,
  });

  return pairings;
};

// -------------------------------------------------------------- CSS output

const block = (tokens: Tokens): string =>
  Object.entries(tokens)
    .map(([name, value]) => `  --color-${name}: ${value};`)
    .join("\n");

const section = (role: Tokens, extension: Tokens): string =>
  [
    "  /* MD3 roles. */",
    block(role),
    "",
    "  /* Theme-invariant, on purpose — see the note above. */",
    block(THEME_INVARIANT),
    "",
    "  /* Extensions: what MD3 has no role for. None may duplicate one. */",
    block(extension),
  ].join("\n");

const render = (): string => {
  const darkRole = roleTokens("dark");
  const lightRole = roleTokens("light");
  const darkExtension = extensionTokens("dark");
  const lightExtension = extensionTokens("light");

  return `${START}
/**
 * Material Design 3 colour tokens, generated from the seed ${SEED}.
 *
 * Do not hand-edit between these markers; run
 * \`npx tsx scripts/generate-md3-tokens.ts\` instead. Every value below is a
 * tone sampled from a tonal palette, so contrast is a property of the tone
 * pair rather than something checked afterwards — and the generator refuses to
 * emit a palette whose text pairings fall below AA.
 *
 * \`@theme\` carries the dark values because dark is the fallback when a reader
 * has expressed no preference. The two \`[data-theme]\` blocks then set the
 * palette explicitly, and an inline script in index.html stamps that attribute
 * before first paint, so there is no flash of the wrong theme.
 */
@theme {
${section(darkRole, darkExtension)}
}

:root[data-theme="dark"] {
${section(darkRole, darkExtension)}

  color-scheme: dark;
}

:root[data-theme="light"] {
${section(lightRole, lightExtension)}

  color-scheme: light;
}
${END}`;
};

// ------------------------------------------------------------------- main

const check = process.argv.includes("--check");

const darkTokens = {
  ...roleTokens("dark"),
  ...THEME_INVARIANT,
  ...extensionTokens("dark"),
};
const lightTokens = {
  ...roleTokens("light"),
  ...THEME_INVARIANT,
  ...extensionTokens("light"),
};

const pairings = [
  ...pairingsFor("dark", darkTokens),
  ...pairingsFor("light", lightTokens),
];

/**
 * Headroom, not ratio, is what says whether a pairing is safe.
 *
 * A text pairing at 4.83 and a graphic pairing at 4.83 are not equally healthy:
 * the first is 0.33 above its floor and the second is 1.83 above a different
 * one. Reporting the raw ratio invites reading "it passes" as "there is room",
 * which is how a retoning in a later phase turns a thin pass into a failure
 * that nobody saw coming. So the report is sorted by margin and names the floor.
 */
const measured = pairings
  .map((pairing) => {
    const ratio = contrastRatio(pairing.fg, pairing.bg);
    return { ...pairing, ratio, headroom: ratio - pairing.floor };
  })
  .sort((a, b) => a.headroom - b.headroom);

/**
 * No extension may be a second name for a role.
 *
 * This is the defect M6 spent 51 call sites clearing, made unrepeatable. Before
 * it the palette carried seven colours twice — `error` was emitted,
 * contrast-gated and rendered nowhere while the app's error colour reached the
 * page as `negative-ink` — and which name a component used was a matter of when
 * the line was written.
 *
 * Checked in **both** themes, and that is the whole subtlety. `ink-faint` and
 * `outline` are the same value on dark and different on light, because the
 * light theme's faint tone was pulled from 50 to 45 to clear AA against
 * `surface-container`. A guard reading one theme would demand they be merged
 * and take that correction with them; a rename driven by hex equality in one
 * theme is exactly the mistake this refuses.
 */
const assertNoRoleDuplicates = () => {
  const roles = Object.keys(roleTokens("dark"));
  const extensions = Object.keys(extensionTokens("dark"));

  const clashes = extensions.flatMap((ext) =>
    roles
      .filter(
        (role) =>
          darkTokens[ext] === darkTokens[role] &&
          lightTokens[ext] === lightTokens[role],
      )
      .map((role) => `  ${ext} is ${role} under another name`),
  );

  if (clashes.length > 0) {
    console.error(
      `\nDuplicate-role gate FAILED:\n${clashes.join("\n")}\n\n` +
        "An extension exists because MD3 has no role for it. Spell the role at " +
        "the call sites instead, and delete the alias.",
    );
    process.exit(1);
  }

  console.log(
    `Duplicate-role gate passed (${extensions.length} extensions, none shadowing a role).`,
  );
};

assertNoRoleDuplicates();

const failures = measured.filter((m) => m.ratio < m.floor);
const worstText = Math.min(
  ...measured.filter((m) => m.floor >= 4.5).map((m) => m.ratio),
);

console.log(`seed ${SEED} -> hue ${seed.hue.toFixed(1)}, chroma ${seed.chroma.toFixed(1)}, tone ${seed.tone.toFixed(1)}`);
console.log(`${pairings.length} pairings checked, worst text pairing ${worstText.toFixed(2)}:1`);

if (failures.length > 0) {
  console.error(
    `\nContrast gate FAILED:\n${failures
      .map((m) => `  ${m.label}: ${m.ratio.toFixed(2)}:1 (needs ${m.floor})`)
      .join("\n")}`,
  );
  process.exit(1);
}

console.log("Contrast gate passed (AA for text, 3:1 for non-text).");

const row = (m: (typeof measured)[number]) =>
  `  +${m.headroom.toFixed(2)}  ${m.ratio.toFixed(2)}:1 vs ${m.floor.toFixed(1)} floor  ${m.label}`;

// Split live from latent. Both are enforced, but a phase deciding where to
// spend headroom should not be led by a combination nothing paints.
console.log("\nTightest margins that something actually renders:");
for (const m of measured.filter((m) => m.live).slice(0, 5)) console.log(row(m));

console.log("\nTightest latent pairings (checked, but no call site today):");
for (const m of measured.filter((m) => !m.live).slice(0, 3)) console.log(row(m));
console.log();

const css = readFileSync(CSS_PATH, "utf8");
const startAt = css.indexOf(START);
const endAt = css.indexOf(END);
if (startAt === -1 || endAt === -1) {
  console.error(`Markers not found in ${CSS_PATH}. Add ${START} / ${END} first.`);
  process.exit(1);
}

const next = css.slice(0, startAt) + render() + css.slice(endAt + END.length);

if (check) {
  if (next !== css) {
    console.error("src/index.css is out of date — run without --check to regenerate.");
    process.exit(1);
  }
  console.log("src/index.css matches the generator.");
} else {
  writeFileSync(CSS_PATH, next);
  console.log(`Wrote ${CSS_PATH}`);
}
