/**
 * Generates the Material Design 3 colour tokens in `src/index.css`.
 *
 * Rewrites only the region between the MD3-TOKENS markers, so the prose and the
 * `body` rule around it stay hand-editable. Re-running is deterministic: same
 * seed in, same hexes out.
 *
 * Run: `npx tsx scripts/generate-md3-tokens.ts`
 *      `npx tsx scripts/generate-md3-tokens.ts --check`  (CI / pre-commit)
 *
 * The `--check` mode regenerates into memory and diffs against the file, so a
 * hand-edited hex is caught rather than silently overwritten on the next run.
 *
 * See `docs/roadmap.md` phase M1. This script is the derivation *and* the
 * contrast gate: it refuses to emit a palette whose text pairings fall below
 * WCAG AA, because "contrast is measured, not eyeballed" is a constraint the
 * roadmap records and a redesign is exactly how it gets lost.
 */
import { readFileSync, writeFileSync } from "node:fs";

import { blend, contrastRatio, hctFromHex, tonalPalette } from "@/md3-color-core";

const CSS_PATH = new URL("../src/index.css", import.meta.url).pathname;
const START = "/* MD3-TOKENS:START — generated by scripts/generate-md3-tokens.ts */";
const END = "/* MD3-TOKENS:END */";

// ---------------------------------------------------------------- the seed

/**
 * The seed. Chosen as the app's existing accent so the migration re-derives the
 * palette the reader already knows rather than rebranding underneath them.
 */
const SEED = "#10b981";

/**
 * MD3 derives every palette from the seed hue, including the neutrals. Here
 * that would tint every surface green, which is a *larger* change than the one
 * being asked for — the app's surfaces are slate today and the seed is an
 * emerald 90 degrees away. So the neutral hue is pinned to the existing slate
 * and only the accent palettes follow the seed. Material's own `DynamicScheme`
 * takes explicit neutral palettes for exactly this reason; it is a supported
 * configuration, not a departure from the system.
 *
 * Raise `NEUTRAL_CHROMA` toward 12 to bring back more of slate's blue cast;
 * MD3's own value is 6, and the surfaces read greyer at it than they do today.
 */
const NEUTRAL_HUE = 258;
const NEUTRAL_CHROMA = 6;
const NEUTRAL_VARIANT_CHROMA = 8;

const seed = hctFromHex(SEED);

const primary = tonalPalette(seed.hue, 48);
const secondary = tonalPalette(seed.hue, 16);
const tertiary = tonalPalette(seed.hue + 60, 24);
const neutral = tonalPalette(NEUTRAL_HUE, NEUTRAL_CHROMA);
const neutralVariant = tonalPalette(NEUTRAL_HUE, NEUTRAL_VARIANT_CHROMA);
/** MD3's fixed error palette — the one part of the system that ignores the seed. */
const error = tonalPalette(25, 84);
/**
 * `warning` has no MD3 role. MD3 handles this as an "extended colour": a colour
 * outside the scheme gets its own tonal palette and the same tone assignments,
 * so it behaves like a role even though the spec does not name it. Seeded from
 * the amber shipping today so the meaning survives the migration.
 */
const warning = (() => {
  const amber = hctFromHex("#f59e0b");
  return tonalPalette(amber.hue, amber.chroma);
})();

// ------------------------------------------------------------- tone mapping

interface Tokens {
  [name: string]: string;
}

/**
 * Tokens that are deliberately identical in both themes, and must not be swept
 * into the tonal system.
 *
 * `scrim` is MD3's own (neutral tone 0) and was already black here. The `plate`
 * trio is ours: broadcaster marks are dark artwork on transparent grounds, so
 * they need a light backing in *both* themes or they vanish on a dark page.
 * Deriving these from a palette is the obvious-looking change that breaks them.
 */
const THEME_INVARIANT: Tokens = {
  scrim: "#000000",
  plate: "#ffffff",
  "plate-line": "#d8dee7",
  "plate-ink": "#0f172a",
};

const roleTokens = (mode: "dark" | "light"): Tokens => {
  const dark = mode === "dark";
  const t = <T>(darkValue: T, lightValue: T): T => (dark ? darkValue : lightValue);

  return {
    // ---- MD3 accent roles
    primary: primary(t(80, 40)),
    "on-primary": primary(t(20, 100)),
    "primary-container": primary(t(30, 90)),
    "on-primary-container": primary(t(90, 10)),

    secondary: secondary(t(80, 40)),
    "on-secondary": secondary(t(20, 100)),
    "secondary-container": secondary(t(30, 90)),
    "on-secondary-container": secondary(t(90, 10)),

    tertiary: tertiary(t(80, 40)),
    "on-tertiary": tertiary(t(20, 100)),
    "tertiary-container": tertiary(t(30, 90)),
    "on-tertiary-container": tertiary(t(90, 10)),

    error: error(t(80, 40)),
    "on-error": error(t(20, 100)),
    "error-container": error(t(30, 90)),
    "on-error-container": error(t(90, 10)),

    // ---- MD3 surface roles. The container ladder replaces shadow-based
    // elevation: a "higher" surface is a lighter tone, which is what keeps a
    // dark theme legible where drop shadows cannot be seen at all.
    surface: neutral(t(6, 98)),
    "surface-container-lowest": neutral(t(4, 100)),
    "surface-container-low": neutral(t(10, 96)),
    "surface-container": neutral(t(12, 94)),
    "surface-container-high": neutral(t(17, 92)),
    "surface-container-highest": neutral(t(22, 90)),
    "on-surface": neutral(t(90, 10)),
    "on-surface-variant": neutralVariant(t(80, 30)),

    outline: neutralVariant(t(60, 50)),
    "outline-variant": neutralVariant(t(30, 80)),

    "inverse-surface": neutral(t(90, 20)),
    "inverse-on-surface": neutral(t(20, 95)),
    "inverse-primary": primary(t(40, 80)),
  };
};

/**
 * The names components actually use today, mapped onto the roles above.
 *
 * M1 changes values, not call sites: keeping these aliases for one phase means
 * a visual regression has exactly one possible cause. `docs/roadmap.md` records
 * the mapping; the odd one out is `surface`, which in MD3 means the *page* but
 * here still means a card. That rename lands in M2 along with the component
 * edits, rather than being smuggled into the phase that changes every colour.
 */
const legacyTokens = (mode: "dark" | "light", role: Tokens): Tokens => {
  const dark = mode === "dark";
  const t = <T>(darkValue: T, lightValue: T): T => (dark ? darkValue : lightValue);

  return {
    canvas: role.surface,
    // TODO(M2): rename to `card`; MD3 spells this `surface-container-low`.
    surface: role["surface-container-low"],
    raised: role["surface-container"],
    "raised-strong": role["surface-container-high"],

    line: role["outline-variant"],
    "line-strong": role.outline,

    ink: role["on-surface"],
    "ink-soft": neutralVariant(t(80, 30)),
    "ink-muted": neutralVariant(t(70, 40)),
    // Light's faint tones run darker than the dark theme's run light. The
    // backgrounds are not mirror images — `raised` sits at tone 94 on light but
    // tone 12 on dark, so the light theme has much less room beneath it before
    // AA fails. Tone 50 here measured 3.86:1 against `raised`; 45 clears it.
    "ink-faint": neutralVariant(t(60, 45)),
    "ink-ghost": neutralVariant(t(50, 55)),
    "ink-inverted": role["inverse-on-surface"],

    positive: primary(t(70, 60)),
    "positive-ink": primary(t(80, 40)),
    negative: error(t(60, 50)),
    "negative-ink": error(t(80, 40)),
    warning: warning(t(70, 70)),
    "warning-ink": warning(t(85, 40)),
  };
};

// ----------------------------------------------------------- contrast gate

interface Pairing {
  label: string;
  fg: string;
  bg: string;
  floor: number;
  /** False when no component paints this combination today — see `backgroundsFor`. */
  live: boolean;
}

/**
 * The backgrounds text is actually painted on — which is not the same as the
 * list of background tokens.
 *
 * A filled `Surface` is `bg-surface/50`, not `bg-surface`, so the colour behind
 * a card's text is a composite of `surface` over `canvas`. Measuring against the
 * solid token instead flatters the light theme by roughly a tenth of a point,
 * in the theme that has the least headroom to give. `MatchPage`'s article is the
 * same 50% fill; `PlayerOverlayCard`, the table headers and the round selector
 * use the solid token, so both are real and both are measured.
 *
 * `live: false` marks a combination no component currently paints. Those are
 * still checked — a latent pairing below AA is a trap that springs the first
 * time someone reaches for it — but a phase spending its scarcest headroom
 * should know it is protecting something nobody renders yet.
 */
const backgroundsFor = (
  tokens: Tokens,
): { name: string; hex: string; live: (fg: string) => boolean }[] => [
  { name: "canvas", hex: tokens.canvas, live: () => true },
  { name: "surface", hex: tokens.surface, live: () => true },
  {
    name: "surface/50 over canvas (filled Surface)",
    hex: blend(tokens.surface, tokens.canvas, 0.5),
    live: () => true,
  },
  {
    name: "raised",
    hex: tokens.raised,
    // Every `bg-raised` call site — the status badges in MatchList and
    // MatchPage, and the Button and NavBar hover states — pairs with `ink-soft`
    // or `ink-muted`. Nothing paints the fainter inks on it.
    live: (fg) => fg === "ink" || fg === "ink-soft" || fg === "ink-muted",
  },
];

const pairingsFor = (mode: string, tokens: Tokens): Pairing[] => {
  const backgrounds = backgroundsFor(tokens);
  const text = [
    "ink",
    "ink-soft",
    "ink-muted",
    "ink-faint",
    "positive-ink",
    "negative-ink",
    "warning-ink",
  ];

  const pairings: Pairing[] = [];
  for (const fg of text) {
    for (const bg of backgrounds) {
      pairings.push({
        label: `${mode}: ${fg} on ${bg.name}`,
        fg: tokens[fg],
        bg: bg.hex,
        floor: 4.5,
        live: bg.live(fg),
      });
    }
  }

  // Non-text: `ink-ghost` backs underline decoration and the large score
  // separator, so the 3:1 floor applies rather than AA.
  for (const bg of backgrounds) {
    pairings.push({
      label: `${mode}: ink-ghost on ${bg.name} (non-text)`,
      fg: tokens["ink-ghost"],
      bg: bg.hex,
      floor: 3,
      live: bg.live("ink-ghost"),
    });
  }

  // The current nav entry is a filled chip: ink background, inverted text.
  pairings.push({
    label: `${mode}: ink-inverted on ink (nav chip)`,
    fg: tokens["ink-inverted"],
    bg: tokens.ink,
    floor: 4.5,
    live: true,
  });
  pairings.push({
    label: `${mode}: plate-ink on plate`,
    fg: tokens["plate-ink"],
    bg: tokens.plate,
    floor: 4.5,
    live: true,
  });

  // MD3's own promise: every `on-` role is readable on its pair. No component
  // names these yet — the roles ship in M1 and the call sites arrive in M2 — but
  // the guarantee is the reason to adopt the system, so it is checked from now.
  for (const role of ["primary", "secondary", "tertiary", "error"]) {
    pairings.push({
      label: `${mode}: on-${role} on ${role}`,
      fg: tokens[`on-${role}`],
      bg: tokens[role],
      floor: 4.5,
      live: false,
    });
    pairings.push({
      label: `${mode}: on-${role}-container on ${role}-container`,
      fg: tokens[`on-${role}-container`],
      bg: tokens[`${role}-container`],
      floor: 4.5,
      live: false,
    });
  }
  pairings.push({
    label: `${mode}: on-surface-variant on surface`,
    fg: tokens["on-surface-variant"],
    bg: tokens.surface,
    floor: 4.5,
    live: false,
  });

  return pairings;
};

// -------------------------------------------------------------- CSS output

const block = (tokens: Tokens, skip: readonly string[] = []): string =>
  Object.entries(tokens)
    .filter(([name]) => !skip.includes(name))
    .map(([name, value]) => `  --color-${name}: ${value};`)
    .join("\n");

/**
 * MD3's `surface` role is not emitted under that name.
 *
 * It means the page, but this codebase has spelled the page `canvas` since
 * before the migration and spells a *card* `surface`. Emitting both would
 * declare `--color-surface` twice in one block and leave the winner to
 * source order — which happens to be right today and would stop being right
 * the moment the generator reorders. `canvas` carries the role until M2
 * renames the call sites.
 */
const ROLES_EMITTED_AS_LEGACY = ["surface"] as const;

const section = (role: Tokens, legacy: Tokens): string =>
  [
    "  /* MD3 roles. `surface` is spelled `canvas` below until M2. */",
    block(role, ROLES_EMITTED_AS_LEGACY),
    "",
    "  /* Theme-invariant, on purpose — see the note above. */",
    block(THEME_INVARIANT),
    "",
    "  /* The names components use today, mapped onto the roles above. */",
    block(legacy),
  ].join("\n");

const render = (): string => {
  const darkRole = roleTokens("dark");
  const lightRole = roleTokens("light");
  const darkLegacy = legacyTokens("dark", darkRole);
  const lightLegacy = legacyTokens("light", lightRole);

  return `${START}
/**
 * Material Design 3 colour tokens, generated from the seed ${SEED}.
 *
 * Do not hand-edit between these markers; run
 * \`npx tsx scripts/generate-md3-tokens.ts\` instead. Every value below is a
 * tone sampled from a tonal palette, so contrast is a property of the tone
 * pair rather than something checked afterwards — and the generator refuses to
 * emit a palette whose text pairings fall below AA.
 *
 * \`@theme\` carries the dark values because dark is the fallback when a reader
 * has expressed no preference. The two \`[data-theme]\` blocks then set the
 * palette explicitly, and an inline script in index.html stamps that attribute
 * before first paint, so there is no flash of the wrong theme.
 */
@theme {
${section(darkRole, darkLegacy)}
}

:root[data-theme="dark"] {
${section(darkRole, darkLegacy)}

  color-scheme: dark;
}

:root[data-theme="light"] {
${section(lightRole, lightLegacy)}

  color-scheme: light;
}
${END}`;
};

// ------------------------------------------------------------------- main

const check = process.argv.includes("--check");

const darkTokens = {
  ...roleTokens("dark"),
  ...THEME_INVARIANT,
  ...legacyTokens("dark", roleTokens("dark")),
};
const lightTokens = {
  ...roleTokens("light"),
  ...THEME_INVARIANT,
  ...legacyTokens("light", roleTokens("light")),
};

const pairings = [
  ...pairingsFor("dark", darkTokens),
  ...pairingsFor("light", lightTokens),
];

/**
 * Headroom, not ratio, is what says whether a pairing is safe.
 *
 * A text pairing at 4.83 and a graphic pairing at 4.83 are not equally healthy:
 * the first is 0.33 above its floor and the second is 1.83 above a different
 * one. Reporting the raw ratio invites reading "it passes" as "there is room",
 * which is how a retoning in a later phase turns a thin pass into a failure
 * that nobody saw coming. So the report is sorted by margin and names the floor.
 */
const measured = pairings
  .map((pairing) => {
    const ratio = contrastRatio(pairing.fg, pairing.bg);
    return { ...pairing, ratio, headroom: ratio - pairing.floor };
  })
  .sort((a, b) => a.headroom - b.headroom);

const failures = measured.filter((m) => m.ratio < m.floor);
const worstText = Math.min(
  ...measured.filter((m) => m.floor >= 4.5).map((m) => m.ratio),
);

console.log(`seed ${SEED} -> hue ${seed.hue.toFixed(1)}, chroma ${seed.chroma.toFixed(1)}, tone ${seed.tone.toFixed(1)}`);
console.log(`${pairings.length} pairings checked, worst text pairing ${worstText.toFixed(2)}:1`);

if (failures.length > 0) {
  console.error(
    `\nContrast gate FAILED:\n${failures
      .map((m) => `  ${m.label}: ${m.ratio.toFixed(2)}:1 (needs ${m.floor})`)
      .join("\n")}`,
  );
  process.exit(1);
}

console.log("Contrast gate passed (AA for text, 3:1 for non-text).");

const row = (m: (typeof measured)[number]) =>
  `  +${m.headroom.toFixed(2)}  ${m.ratio.toFixed(2)}:1 vs ${m.floor.toFixed(1)} floor  ${m.label}`;

// Split live from latent. Both are enforced, but a phase deciding where to
// spend headroom should not be led by a combination nothing paints.
console.log("\nTightest margins that something actually renders:");
for (const m of measured.filter((m) => m.live).slice(0, 5)) console.log(row(m));

console.log("\nTightest latent pairings (checked, but no call site today):");
for (const m of measured.filter((m) => !m.live).slice(0, 3)) console.log(row(m));
console.log();

const css = readFileSync(CSS_PATH, "utf8");
const startAt = css.indexOf(START);
const endAt = css.indexOf(END);
if (startAt === -1 || endAt === -1) {
  console.error(`Markers not found in ${CSS_PATH}. Add ${START} / ${END} first.`);
  process.exit(1);
}

const next = css.slice(0, startAt) + render() + css.slice(endAt + END.length);

if (check) {
  if (next !== css) {
    console.error("src/index.css is out of date — run without --check to regenerate.");
    process.exit(1);
  }
  console.log("src/index.css matches the generator.");
} else {
  writeFileSync(CSS_PATH, next);
  console.log(`Wrote ${CSS_PATH}`);
}
