#!/bin/bash
#
# rehearse-blocklist.sh
# ---------------------
# Behavioural coverage for shell_scripts/15_install_blocklist.sh, which is the
# only coverage it has: `npm run lint` is TypeScript and cannot see shell, and
# CI otherwise only shellchecks it.
#
# It matters more than a shellcheck because that script **ships inside the
# release tarball** and writes nginx config on the host. Its failure mode is the
# site going off the air, and the four refusals it carries are the whole reason
# it is a script rather than a one-line `tee`.
#
# Hermetic: bash, coreutils, no network, no root, no real nginx. `nginx` and
# `systemctl` are stubs, and the config is written into a temp directory — so a
# green run here means THIS COMMIT is sound, never that somebody's server had a
# good minute. That is the same bar rehearse-traffic-report.sh is held to.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SCRIPT_UNDER_TEST="$ROOT/shell_scripts/15_install_blocklist.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

ok=0
bad=0

check() {
    local label="$1" want="$2" got="$3"
    if [[ "$want" == "$got" ]]; then
        echo "ok   — $label"
        ok=$((ok + 1))
    else
        echo "NOT OK — $label (want: $want, got: $got)"
        bad=$((bad + 1))
    fi
}

contains() {
    local label="$1" needle="$2" file="$3"
    if grep -qF "$needle" "$file" 2>/dev/null; then
        echo "ok   — $label"
        ok=$((ok + 1))
    else
        echo "NOT OK — $label (missing: $needle)"
        bad=$((bad + 1))
    fi
}

absent() {
    local label="$1" needle="$2" file="$3"
    # A missing file has no needle in it, so without this the assertion passes
    # vacuously — which it did through an entire broken run of this harness
    # before the sudo stub existed. "Not present" has to mean the file was read.
    if [[ ! -f "$file" ]]; then
        echo "NOT OK — $label (the file does not exist: $file)"
        bad=$((bad + 1))
        return
    fi
    if grep -qF "$needle" "$file" 2>/dev/null; then
        echo "NOT OK — $label (present but should not be: $needle)"
        bad=$((bad + 1))
    else
        echo "ok   — $label"
        ok=$((ok + 1))
    fi
}

# ── Stubs ────────────────────────────────────────────────────────────────────
#
# `nginx` accepts or refuses depending on a flag file, so the rollback path can
# be driven without a broken config nginx would have to parse. `systemctl`
# records that it was asked to reload, because "did it reload" is a separate
# question from "did it write the file" and the rollback path must not reload.
mkdir -p "$WORK/bin"
cat > "$WORK/bin/nginx" <<'STUB'
#!/bin/bash
if [[ -f "$NGINX_REFUSES" ]]; then
    echo "nginx: [emerg] stubbed refusal" >&2
    exit 1
fi
echo "syntax is ok"
STUB
cat > "$WORK/bin/systemctl" <<'STUB'
#!/bin/bash
echo "$*" >> "$SYSTEMCTL_LOG"
STUB
# `sudo` is a passthrough, the same stub rehearse-flip-back.sh uses. The script
# genuinely needs root on a real host — `nginx -t` and a reload both do — so it
# is stubbed rather than designed away, and what is exercised is the real
# command it would have run.
cat > "$WORK/bin/sudo" <<'STUB'
#!/bin/bash
# Drop any leading options sudo would have consumed, then exec the command.
while [[ "${1:-}" == -* ]]; do shift; done
exec "$@"
STUB
chmod +x "$WORK/bin/nginx" "$WORK/bin/systemctl" "$WORK/bin/sudo"
export PATH="$WORK/bin:$PATH"
export NGINX_REFUSES="$WORK/refuses"
export SYSTEMCTL_LOG="$WORK/systemctl.log"
: > "$SYSTEMCTL_LOG"

CONF="$WORK/blocklist.conf"

run() {
    # Always unprivileged, so the script's own `sudo` branch is not taken. Under
    # a real root run it would be, and that path is one word different.
    BLOCKLIST_SRC="$1" BLOCKLIST_CONF="$CONF" \
        bash "$SCRIPT_UNDER_TEST" "${2:-}" > "$WORK/out.txt" 2>&1
    echo $?
}

# ── The happy path ───────────────────────────────────────────────────────────
cat > "$WORK/good.txt" <<'EOF'
# a comment, and a blank line follow

203.0.113.7
198.51.100.0/24     # trailing comment on an entry
2001:db8::1
EOF
status="$(run "$WORK/good.txt")"
check "a well-formed list installs" "0" "$status"
contains "the address is rendered as a deny" "deny 203.0.113.7;" "$CONF"
contains "a CIDR survives its trailing comment" "deny 198.51.100.0/24;" "$CONF"
contains "IPv6 is rendered too" "deny 2001:db8::1;" "$CONF"
absent "the comment line is not rendered" "a comment, and a blank" "$CONF"
contains "the file says it is generated" "GENERATED by shell_scripts" "$CONF"
check "nginx was reloaded, not restarted" "1" "$(grep -c 'reload nginx' "$SYSTEMCTL_LOG")"

# ── Idempotent ───────────────────────────────────────────────────────────────
before="$(grep -c '^deny ' "$CONF")"
status="$(run "$WORK/good.txt")"
check "re-running is safe" "0" "$status"
check "and does not accumulate duplicates" "$before" "$(grep -c '^deny ' "$CONF")"

# ── An EMPTY list is valid: it is how you unblock everybody ──────────────────
printf '# nothing blocked\n' > "$WORK/empty.txt"
status="$(run "$WORK/empty.txt")"
check "an empty list installs rather than erroring" "0" "$status"
check "and writes a file with no denies at all" "0" "$(grep -c '^deny ' "$CONF")"

# ── Refusal 1: a malformed entry, named by line ──────────────────────────────
: > "$SYSTEMCTL_LOG"
cp "$CONF" "$WORK/before-bad.conf"
printf '203.0.113.7\nnot-an-ip-at-all\n' > "$WORK/malformed.txt"
status="$(run "$WORK/malformed.txt")"
check "a malformed entry exits 1" "1" "$status"
contains "and says which line" "line 2" "$WORK/out.txt"
check "nothing was written" "0" "$(diff -q "$CONF" "$WORK/before-bad.conf" >/dev/null && echo 0 || echo 1)"
check "and nginx was not reloaded" "0" "$(grep -c 'reload' "$SYSTEMCTL_LOG")"

# ── Refusal 2: a /0 takes the whole site off the air ─────────────────────────
printf '0.0.0.0/0\n' > "$WORK/catchall.txt"
status="$(run "$WORK/catchall.txt")"
check "a /0 catch-all exits 1" "1" "$status"
contains "and says it blocks everything" "blocks EVERYTHING" "$WORK/out.txt"

# ── Refusal 3: the address you are connected from ────────────────────────────
#
# The incident this came from: proving a deny works by blocking one's own
# address locked the operator out, and the cleanup then killed its own ssh
# session before undoing it. SSH_CLIENT is what the host already knows.
printf '203.0.113.7\n198.51.100.44\n' > "$WORK/self.txt"
status="$(SSH_CLIENT="198.51.100.44 55000 22" run "$WORK/self.txt")"
check "blocking your own address exits 1" "1" "$status"
contains "and names the address" "198.51.100.44" "$WORK/out.txt"
status="$(SSH_CLIENT="198.51.100.44 55000 22" ALLOW_SELF_BLOCK=true run "$WORK/self.txt")"
check "ALLOW_SELF_BLOCK is the deliberate override" "0" "$status"
contains "and it really does install it" "deny 198.51.100.44;" "$CONF"

# ── Refusal 4: nginx rejects the result, so the previous file comes back ─────
#
# The one that must never fail: a blocklist may not be able to take the site
# down. Driven with a stub refusal rather than a genuinely broken config,
# because validation above means the script cannot easily be made to emit one.
status="$(run "$WORK/good.txt")"
check "a good install first, to have something to roll back TO" "0" "$status"
cp "$CONF" "$WORK/known-good.conf"
: > "$SYSTEMCTL_LOG"
touch "$NGINX_REFUSES"
printf '203.0.113.99\n' > "$WORK/other.txt"
status="$(run "$WORK/other.txt")"
rm -f "$NGINX_REFUSES"
check "an nginx refusal exits 2, not 1" "2" "$status"
check "the PREVIOUS config is back byte for byte" "0" \
    "$(diff -q "$CONF" "$WORK/known-good.conf" >/dev/null && echo 0 || echo 1)"
absent "and the rejected address is not in it" "deny 203.0.113.99;" "$CONF"
check "nginx was NOT reloaded onto a config it rejected" "0" "$(grep -c 'reload' "$SYSTEMCTL_LOG")"

# ── --dry-run changes nothing ────────────────────────────────────────────────
: > "$SYSTEMCTL_LOG"
cp "$CONF" "$WORK/before-dry.conf"
status="$(run "$WORK/other.txt" --dry-run)"
check "--dry-run exits 0" "0" "$status"
contains "and prints what it would write" "deny 203.0.113.99;" "$WORK/out.txt"
check "but the file is untouched" "0" \
    "$(diff -q "$CONF" "$WORK/before-dry.conf" >/dev/null && echo 0 || echo 1)"
check "and nothing was reloaded" "0" "$(grep -c 'reload' "$SYSTEMCTL_LOG")"

# ── A missing list is an error, and a loud one ───────────────────────────────
status="$(run "$WORK/nope.txt")"
check "a missing list exits 1" "1" "$status"
contains "and says which path it looked at" "$WORK/nope.txt" "$WORK/out.txt"

echo
echo "$ok ok / $bad not ok"
[[ "$bad" -eq 0 ]]
