/**
 * Renders the two data files `scripts/sync-goals.ts` writes —
 * `src/data/goals.ts` and `src/data/escalacoes.ts`. One module because one run
 * writes both, from one request per match, which is the same reason the sync
 * itself is not split in two.
 *
 * **It is a module rather than a heredoc inside the sync for one reason: the
 * committed file has to be byte-identical to what the next sync would write.**
 * The tuple encoding landed by re-rendering the data already on disk rather
 * than by re-fetching 252 matches from a host that throttles at the socket, and
 * a second copy of this formatting — even one that looked right — would have
 * left the next real sync rewriting all 258 lines with a diff nobody could read
 * and no way to tell a formatting change from a data change.
 *
 * The encoding itself is `encodeLineups` in `escalacao-core.ts`, beside the
 * decoder that reads it back; this file only decides where the newlines go.
 */
import { encodeLineups } from "@/escalacao-core";
import { encodeGoals } from "@/goals-core";
import type { Goal, Lineup } from "@/src/types";

const j = JSON.stringify;

/**
 * One fixture per line.
 *
 * Not prettier than that, and deliberately: 252 lines of tuples is a file
 * `git diff` can report a changed *fixture* in, where one row per player put
 * 18 016 lines in front of a reader looking for the one that moved. It is the
 * shape `club-scouts-history.ts` already takes, for the same reason.
 */
const renderLineups = (lineups: Lineup[]): string =>
  encodeLineups(lineups)
    .map(
      ([clubCode, players, subs]) =>
        `[${j(clubCode)},[` +
        players.map((p) => `[${p.map((field) => j(field)).join(",")}]`).join(",") +
        `]` +
        (subs ? `,[` + subs.map((s) => `[${s.map((field) => j(field)).join(",")}]`).join(",") + `]` : "") +
        `]`,
    )
    .join(",");

export const renderLineupsFile = (
  lineupsByMatch: Record<string, Lineup[]>,
  generatedOn: string,
): string => {
  const ids = Object.keys(lineupsByMatch).sort((a, b) => Number(a) - Number(b));
  return `import { decodeLineups } from "@/escalacao-core";
import type { Lineup, LineupEntry } from "@/src/types";

/**
 * GENERATED by scripts/sync-goals.ts — the same run that writes goals.ts.
 *
 * **One script, because the escalação is in the payload the goals already
 * arrive in.** A second sync would have walked the same listing, resolved the
 * same join and re-fetched every match — doubling the traffic against a host
 * that throttles at the socket with no 429 to warn you.
 *
 * Who started and who was on the bench, keyed by **our** match id. Every entry
 * carries two complete sheets of eleven starters; \`lineupsReconcile\` refuses
 * anything less, so an absent match means "not synced or not published", never
 * "no lineup".
 *
 * **Stored as tuples, one fixture per line, and read back through
 * \`decodeLineups\`.** \`LineupEntry\` in \`src/types.ts\` carries the encoding and
 * the measurements that chose it; the short version is that this file was
 * 791.7 KB as objects and is 318.3 KB as tuples, and that converting it to JSON
 * instead would have saved half as much while giving up the typecheck. Those two
 * figures are a reading taken when the encoding landed, over 252 fixtures — the
 * file grows, so measure it rather than quoting them.
 *
 * **Nothing outside this file sees a tuple.** \`LINEUPS\` is \`Lineup[]\` exactly
 * as it always was, which is why no component, no core module and no test
 * changed when the encoding did.
 *
 * Generated ${generatedOn}.
 */
const ENTRIES: Record<string, LineupEntry[]> = {
${ids.map((id) => `  ${j(id)}: [${renderLineups(lineupsByMatch[id])}],`).join("\n")}
};

/**
 * Decoded once at import, for every fixture the file holds.
 *
 * Eager rather than per-lookup because \`withLineups\` attaches the whole season
 * to \`/api/matches\` anyway, so a lazy decode would buy nothing and would owe a
 * cache. **8 ms for the whole file**, measured over 252 fixtures when this
 * landed — once, at import, against a server that then answers from a 60s
 * cache.
 */
export const LINEUPS: Record<string, Lineup[]> = Object.fromEntries(
  Object.entries(ENTRIES).map(([id, entries]) => [id, decodeLineups(entries)]),
);
`;
};

/**
 * One match per line, `renderLineupsFile`'s shape and for its reason.
 *
 * The header keeps saying **safe to hand-edit**, and that is a promise this
 * encoding makes harder to keep rather than one it withdraws — so the shape of
 * a row is spelled out in the generated file itself, where somebody adding a
 * goal will be standing. The case it exists for is real: the sync refuses a
 * match whose `resultado` it does not recognise, and filling one in by hand is
 * how those refusals were always meant to be recoverable.
 */
export const renderGoalsFile = (
  goals: Record<string, Goal[]>,
  generatedOn: string,
): string => {
  const body = Object.keys(goals)
    .sort((a, b) => Number(a) - Number(b))
    .map(
      (id) =>
        "  " +
        j(id) +
        ": [" +
        encodeGoals(goals[id])
          .map((entry) => "[" + entry.map((field) => j(field)).join(",") + "]")
          .join(",") +
        "],",
    )
    .join("\n");

  return `import { decodeGoals } from "@/goals-core";
import type { Goal, GoalEntry } from "@/src/types";

/**
 * GENERATED by scripts/sync-goals.ts — but safe to hand-edit.
 *
 * Who scored, per match. **No football-data tier this app can reach carries
 * goal events** — verified against a live Série A match and a live Premier
 * League one, both free, both answering with no \`goals\` key at all — so this
 * comes from CBF's own match endpoint, read on a workstation and never by the
 * running app. See \`docs/data-sources.md\`.
 *
 * Keyed by **our** match id, for the reason \`broadcasts.ts\` is: CBF's ids are
 * its own.
 *
 * **Every entry here has been reconciled against its own scoreline** — the
 * goals attributed to each club add up to that club's score, checked both
 * against CBF's reported score and against ours — and the sync refuses to write
 * one that does not. A missing match means "not synced, or did not reconcile",
 * never "goalless": a real 0-0 is deliberately absent rather than an empty
 * array, since the two would be indistinguishable here.
 *
 * **Stored as tuples, one match per line, read back through \`decodeGoals\`.**
 * A row is \`[clubCode, scorer, minute?, kind?]\`:
 *
 *     ["1769","Lopez","26'"]                 an ordinary goal
 *     ["1766","Khellven","73'","own"]        counts for 1766, scored by a 1769 player
 *     ["1772","Walter Clar","15'","penalty"]
 *
 * \`minute\` precedes \`kind\` because a tuple cannot skip a middle element and 665
 * of 669 goals carry one. **To add a goal by hand, write a tuple** — \`GoalEntry\`
 * in \`src/types.ts\` has the field list, and \`tsc\` checks the kind against
 * \`GoalKind\` just as it checked the old object literal. Nothing outside this
 * file sees a tuple: \`GOALS\` is \`Goal[]\` exactly as it always was.
 *
 * Last synced ${generatedOn}.
 */
const ENTRIES: Record<string, GoalEntry[]> = {
${body}
};

export const GOALS: Record<string, Goal[]> = Object.fromEntries(
  Object.entries(ENTRIES).map(([id, entries]) => [id, decodeGoals(entries)]),
);
`;
};
