/**
 * GENERATED by scripts/sync-broadcasts.ts — but safe to hand-edit.
 *
 * The script merges rather than replaces, so entries added by hand survive a
 * later sync (use --replace to start clean). Transcribing from a screenshot
 * remains a supported way to add a fixture.
 *
 * Source: CBF's Onde Assistir API, an undocumented internal endpoint. It is read
 * here, on a workstation, and never by the running app — see
 * docs/data-sources.md.
 *
 * Keyed by **our** match id: CBF's ids are its own, and its three-letter codes
 * are not unique across competitions (one day's page showed `ATH` as both
 * Athletic Club in Série B and Athletico-PR in Série A).
 *
 * Last synced 2026-08-24.
 */
export const BROADCASTS: Record<string, string[]> = {
  "554970": ["Premiere", "SporTV"],
  "554971": ["Globo", "Premiere"],
  "554972": ["Premiere", "Record", "YouTube", "Cazé TV"],
  "554973": ["Premiere"],
  "554974": ["Amazon Prime"],
  "554975": ["Premiere"],
  "554976": ["Premiere", "SporTV"],
  "554977": ["Globo", "Premiere"],
  "554978": ["Premiere"],
  "554979": ["Globo", "Premiere"],
  "554980": ["Premiere"],
  "554981": ["Premiere"],
  "554982": ["Globo", "Premiere"],
  "554983": ["Globo", "Premiere"],
  "554984": ["GE TV", "Globo", "Premiere"],
  "554985": ["Premiere", "SporTV"],
  "554986": ["Amazon Prime"],
  "554987": ["Premiere"],
  "554988": ["Premiere", "SporTV"],
  "554989": ["Premiere", "Record", "YouTube", "Cazé TV"],
  "554990": ["Premiere", "Record", "YouTube", "Cazé TV"],
  "554991": ["Premiere"],
  "554992": ["Amazon Prime"],
  "554993": ["Premiere"],
  "554994": ["Globo", "Premiere"],
  "554995": ["Premiere", "SporTV"],
  "554996": ["Globo", "Premiere"],
  "554997": ["GE TV", "Globo", "Premiere"],
  "554998": ["Premiere"],
  "554999": ["Premiere", "SporTV"],
};
