import type { ClubScouts } from "@/src/types";

/**
 * GENERATED by `npx tsx scripts/sync-cartola-scouts.ts` — do not hand-edit.
 *
 * Season 2026, rodadas 1..25, from caRtola's snapshots of the
 * Cartola FC market (MIT, `henriquepgomide/caRtola`). Written 2026-09-06
 * against the seed snapshot 2026-09-02.
 *
 * These are the per-action counters **no provider this app can reach reports at
 * any tier** — finalizações, desarmes, faltas, cartões, defesas. Read on a
 * workstation and committed; production never fetches caRtola, exactly as it
 * never fetches CBF.
 *
 * `matches` is the number of finished matches these counters actually cover,
 * read from the source's own per-player `jogos_num`. It is **not** a club's
 * `played` in the live table — the source is weekly, so by Saturday the table
 * holds a round these figures do not, and dividing by the live count
 * understates every rate by the amount that reads as a form dip.
 *
 * It is **not the fixture list either, and may sit below it**: caRtola does not
 * always record a match at all. 13 of the 20 clubs are short in 2026, Botafogo
 * by three. Dividing by what was played rather than by what was counted put
 * Athletico-PR at 8,8 finalizações a game (17º de 20) where the covered matches
 * give 9,5 (12º). A club well short of its fixtures is described on a smaller
 * sample than the division around it — the rate is right, the sample is thinner.
 *
 * Stale by construction, like `rank-history.ts`. Regenerate after a
 * `sync-seed-data` run, or when caRtola publishes a further rodada.
 */
export const CLUB_SCOUTS: ClubScouts[] = [
  // Athletico-PR
  { clubCode: "1768", matches: 23, goals: 33, shotsSaved: 77, shotsOff: 98, shotsWoodwork: 11, tackles: 345, foulsCommitted: 312, yellowCards: 44, redCards: 2, saves: 64 },
  // Atlético-MG
  { clubCode: "1766", matches: 24, goals: 31, shotsSaved: 71, shotsOff: 116, shotsWoodwork: 11, tackles: 288, foulsCommitted: 278, yellowCards: 41, redCards: 3, saves: 74 },
  // Bahia
  { clubCode: "1777", matches: 24, goals: 33, shotsSaved: 81, shotsOff: 134, shotsWoodwork: 15, tackles: 362, foulsCommitted: 326, yellowCards: 55, redCards: 3, saves: 85 },
  // Botafogo
  { clubCode: "1770", matches: 21, goals: 34, shotsSaved: 75, shotsOff: 109, shotsWoodwork: 11, tackles: 316, foulsCommitted: 301, yellowCards: 61, redCards: 5, saves: 77 },
  // Bragantino
  { clubCode: "4286", matches: 23, goals: 26, shotsSaved: 82, shotsOff: 160, shotsWoodwork: 7, tackles: 322, foulsCommitted: 340, yellowCards: 64, redCards: 2, saves: 62 },
  // Chapecoense
  { clubCode: "1772", matches: 23, goals: 23, shotsSaved: 61, shotsOff: 132, shotsWoodwork: 3, tackles: 316, foulsCommitted: 284, yellowCards: 51, redCards: 2, saves: 97 },
  // Clube do Remo
  { clubCode: "4287", matches: 25, goals: 29, shotsSaved: 70, shotsOff: 138, shotsWoodwork: 5, tackles: 382, foulsCommitted: 282, yellowCards: 49, redCards: 3, saves: 94 },
  // Corinthians
  { clubCode: "1779", matches: 24, goals: 25, shotsSaved: 63, shotsOff: 129, shotsWoodwork: 4, tackles: 360, foulsCommitted: 336, yellowCards: 62, redCards: 4, saves: 60 },
  // Coritiba
  { clubCode: "4241", matches: 25, goals: 31, shotsSaved: 49, shotsOff: 111, shotsWoodwork: 6, tackles: 328, foulsCommitted: 260, yellowCards: 40, redCards: 7, saves: 89 },
  // Cruzeiro
  { clubCode: "1771", matches: 25, goals: 35, shotsSaved: 87, shotsOff: 145, shotsWoodwork: 2, tackles: 379, foulsCommitted: 353, yellowCards: 60, redCards: 3, saves: 58 },
  // Flamengo
  { clubCode: "1783", matches: 23, goals: 45, shotsSaved: 67, shotsOff: 128, shotsWoodwork: 13, tackles: 338, foulsCommitted: 261, yellowCards: 43, redCards: 6, saves: 66 },
  // Fluminense
  { clubCode: "1765", matches: 24, goals: 38, shotsSaved: 97, shotsOff: 143, shotsWoodwork: 10, tackles: 353, foulsCommitted: 317, yellowCards: 58, redCards: 1, saves: 88 },
  // Grêmio
  { clubCode: "1767", matches: 23, goals: 25, shotsSaved: 56, shotsOff: 108, shotsWoodwork: 5, tackles: 304, foulsCommitted: 299, yellowCards: 54, redCards: 4, saves: 67 },
  // Internacional
  { clubCode: "6684", matches: 25, goals: 25, shotsSaved: 84, shotsOff: 161, shotsWoodwork: 3, tackles: 364, foulsCommitted: 387, yellowCards: 55, redCards: 2, saves: 62 },
  // Mirassol
  { clubCode: "4364", matches: 22, goals: 20, shotsSaved: 71, shotsOff: 121, shotsWoodwork: 4, tackles: 323, foulsCommitted: 285, yellowCards: 57, redCards: 3, saves: 64 },
  // Palmeiras
  { clubCode: "1769", matches: 25, goals: 43, shotsSaved: 69, shotsOff: 140, shotsWoodwork: 7, tackles: 389, foulsCommitted: 341, yellowCards: 46, redCards: 3, saves: 77 },
  // Santos
  { clubCode: "6685", matches: 22, goals: 31, shotsSaved: 54, shotsOff: 122, shotsWoodwork: 5, tackles: 428, foulsCommitted: 285, yellowCards: 63, redCards: 4, saves: 58 },
  // São Paulo
  { clubCode: "1776", matches: 24, goals: 27, shotsSaved: 72, shotsOff: 121, shotsWoodwork: 5, tackles: 350, foulsCommitted: 345, yellowCards: 54, redCards: 1, saves: 64 },
  // Vasco da Gama
  { clubCode: "1780", matches: 23, goals: 27, shotsSaved: 91, shotsOff: 152, shotsWoodwork: 11, tackles: 348, foulsCommitted: 288, yellowCards: 48, redCards: 2, saves: 67 },
  // Vitória
  { clubCode: "1782", matches: 22, goals: 22, shotsSaved: 61, shotsOff: 111, shotsWoodwork: 4, tackles: 310, foulsCommitted: 288, yellowCards: 50, redCards: 3, saves: 74 },
];

/** The last rodada these counters cover. */
export const CLUB_SCOUTS_THROUGH_ROUND = 25;
