import type { ClubScouts } from "@/src/types";

/**
 * GENERATED by `npx tsx scripts/sync-cartola-scouts.ts` — do not hand-edit.
 *
 * Season 2026, rodadas 1..24, from caRtola's snapshots of the
 * Cartola FC market (MIT, `henriquepgomide/caRtola`). Written 2026-09-02
 * against the seed snapshot 2026-08-26.
 *
 * These are the per-action counters **no provider this app can reach reports at
 * any tier** — finalizações, desarmes, faltas, cartões, defesas. Read on a
 * workstation and committed; production never fetches caRtola, exactly as it
 * never fetches CBF.
 *
 * `matches` is the number of finished matches these counters cover, and is
 * **not** a club's `played` in the live table: the source is weekly, so by
 * Saturday the table holds a round these figures do not. Dividing by the live
 * count understates every rate by exactly the amount that reads as a form dip.
 *
 * Stale by construction, like `rank-history.ts`. Regenerate after a
 * `sync-seed-data` run, or when caRtola publishes a further rodada.
 */
export const CLUB_SCOUTS: ClubScouts[] = [
  // Athletico-PR
  { clubCode: "1768", matches: 24, goals: 30, shotsSaved: 71, shotsOff: 95, shotsWoodwork: 11, tackles: 322, foulsCommitted: 297, yellowCards: 42, redCards: 2, saves: 61 },
  // Atlético-MG
  { clubCode: "1766", matches: 23, goals: 29, shotsSaved: 65, shotsOff: 110, shotsWoodwork: 11, tackles: 270, foulsCommitted: 266, yellowCards: 39, redCards: 3, saves: 72 },
  // Bahia
  { clubCode: "1777", matches: 24, goals: 30, shotsSaved: 77, shotsOff: 130, shotsWoodwork: 15, tackles: 343, foulsCommitted: 316, yellowCards: 51, redCards: 2, saves: 84 },
  // Botafogo
  { clubCode: "1770", matches: 23, goals: 34, shotsSaved: 68, shotsOff: 97, shotsWoodwork: 11, tackles: 301, foulsCommitted: 286, yellowCards: 58, redCards: 5, saves: 74 },
  // Bragantino
  { clubCode: "4286", matches: 23, goals: 25, shotsSaved: 80, shotsOff: 158, shotsWoodwork: 7, tackles: 307, foulsCommitted: 327, yellowCards: 60, redCards: 2, saves: 56 },
  // Chapecoense
  { clubCode: "1772", matches: 23, goals: 22, shotsSaved: 53, shotsOff: 115, shotsWoodwork: 3, tackles: 294, foulsCommitted: 274, yellowCards: 49, redCards: 2, saves: 95 },
  // Clube do Remo
  { clubCode: "4287", matches: 24, goals: 27, shotsSaved: 65, shotsOff: 121, shotsWoodwork: 5, tackles: 360, foulsCommitted: 272, yellowCards: 46, redCards: 3, saves: 91 },
  // Corinthians
  { clubCode: "1779", matches: 24, goals: 25, shotsSaved: 61, shotsOff: 121, shotsWoodwork: 4, tackles: 347, foulsCommitted: 327, yellowCards: 58, redCards: 4, saves: 57 },
  // Coritiba
  { clubCode: "4241", matches: 24, goals: 29, shotsSaved: 46, shotsOff: 109, shotsWoodwork: 5, tackles: 318, foulsCommitted: 251, yellowCards: 39, redCards: 7, saves: 85 },
  // Cruzeiro
  { clubCode: "1771", matches: 24, goals: 34, shotsSaved: 82, shotsOff: 143, shotsWoodwork: 2, tackles: 361, foulsCommitted: 341, yellowCards: 59, redCards: 3, saves: 50 },
  // Flamengo
  { clubCode: "1783", matches: 23, goals: 42, shotsSaved: 64, shotsOff: 121, shotsWoodwork: 13, tackles: 322, foulsCommitted: 253, yellowCards: 43, redCards: 6, saves: 62 },
  // Fluminense
  { clubCode: "1765", matches: 24, goals: 35, shotsSaved: 94, shotsOff: 140, shotsWoodwork: 10, tackles: 333, foulsCommitted: 307, yellowCards: 56, redCards: 1, saves: 82 },
  // Grêmio
  { clubCode: "1767", matches: 23, goals: 22, shotsSaved: 54, shotsOff: 104, shotsWoodwork: 5, tackles: 292, foulsCommitted: 288, yellowCards: 51, redCards: 4, saves: 60 },
  // Internacional
  { clubCode: "6684", matches: 24, goals: 23, shotsSaved: 83, shotsOff: 154, shotsWoodwork: 3, tackles: 342, foulsCommitted: 370, yellowCards: 53, redCards: 2, saves: 58 },
  // Mirassol
  { clubCode: "4364", matches: 23, goals: 19, shotsSaved: 67, shotsOff: 117, shotsWoodwork: 4, tackles: 303, foulsCommitted: 269, yellowCards: 55, redCards: 3, saves: 62 },
  // Palmeiras
  { clubCode: "1769", matches: 24, goals: 42, shotsSaved: 67, shotsOff: 134, shotsWoodwork: 7, tackles: 372, foulsCommitted: 330, yellowCards: 46, redCards: 2, saves: 73 },
  // Santos
  { clubCode: "6685", matches: 23, goals: 30, shotsSaved: 52, shotsOff: 119, shotsWoodwork: 4, tackles: 397, foulsCommitted: 262, yellowCards: 59, redCards: 4, saves: 56 },
  // São Paulo
  { clubCode: "1776", matches: 23, goals: 25, shotsSaved: 66, shotsOff: 116, shotsWoodwork: 5, tackles: 332, foulsCommitted: 334, yellowCards: 51, redCards: 1, saves: 62 },
  // Vasco da Gama
  { clubCode: "1780", matches: 23, goals: 24, shotsSaved: 84, shotsOff: 144, shotsWoodwork: 11, tackles: 332, foulsCommitted: 273, yellowCards: 46, redCards: 2, saves: 62 },
  // Vitória
  { clubCode: "1782", matches: 24, goals: 21, shotsSaved: 59, shotsOff: 106, shotsWoodwork: 4, tackles: 296, foulsCommitted: 275, yellowCards: 49, redCards: 3, saves: 68 },
];

/** The last rodada these counters cover. */
export const CLUB_SCOUTS_THROUGH_ROUND = 24;
