import type { ClubScouts } from "@/src/types";

/**
 * GENERATED by `npx tsx scripts/sync-cartola-scouts.ts` — do not hand-edit.
 *
 * Season 2026, rodadas 1..27, from caRtola's snapshots of the
 * Cartola FC market (MIT, `henriquepgomide/caRtola`). Written 2026-09-16
 * against the seed snapshot 2026-09-16.
 *
 * These are the per-action counters **no provider this app can reach reports at
 * any tier** — finalizações, desarmes, faltas, cartões, defesas. Read on a
 * workstation and committed; production never fetches caRtola, exactly as it
 * never fetches CBF.
 *
 * `matches` is the number of finished matches these counters actually cover,
 * read from the source's own per-player `jogos_num`. It is **not** a club's
 * `played` in the live table — the source is weekly, so by Saturday the table
 * holds a round these figures do not, and dividing by the live count
 * understates every rate by the amount that reads as a form dip.
 *
 * It is **not the fixture list either, and may sit below it**: caRtola does not
 * always record a match at all. 13 of the 20 clubs are short in 2026, Botafogo
 * by three. Dividing by what was played rather than by what was counted put
 * Athletico-PR at 8,8 finalizações a game (17º de 20) where the covered matches
 * give 9,5 (14º). A club well short of its fixtures is described on a smaller
 * sample than the division around it — the rate is right, the sample is thinner.
 *
 * Stale by construction, like `rank-history.ts`. Regenerate after a
 * `sync-seed-data` run, or when caRtola publishes a further rodada.
 */
export const CLUB_SCOUTS: ClubScouts[] = [
  // Athletico-PR
  { clubCode: "1768", matches: 24, goals: 34, shotsSaved: 83, shotsOff: 105, shotsWoodwork: 11, tackles: 356, foulsCommitted: 324, yellowCards: 46, redCards: 2, saves: 66 },
  // Atlético-MG
  { clubCode: "1766", matches: 26, goals: 34, shotsSaved: 75, shotsOff: 123, shotsWoodwork: 12, tackles: 320, foulsCommitted: 298, yellowCards: 43, redCards: 3, saves: 79 },
  // Bahia
  { clubCode: "1777", matches: 26, goals: 38, shotsSaved: 90, shotsOff: 143, shotsWoodwork: 16, tackles: 389, foulsCommitted: 360, yellowCards: 59, redCards: 3, saves: 96 },
  // Botafogo
  { clubCode: "1770", matches: 23, goals: 35, shotsSaved: 85, shotsOff: 126, shotsWoodwork: 11, tackles: 346, foulsCommitted: 327, yellowCards: 67, redCards: 5, saves: 89 },
  // Bragantino
  { clubCode: "4286", matches: 25, goals: 27, shotsSaved: 98, shotsOff: 171, shotsWoodwork: 8, tackles: 356, foulsCommitted: 359, yellowCards: 68, redCards: 3, saves: 70 },
  // Chapecoense
  { clubCode: "1772", matches: 25, goals: 26, shotsSaved: 66, shotsOff: 138, shotsWoodwork: 3, tackles: 349, foulsCommitted: 323, yellowCards: 61, redCards: 2, saves: 104 },
  // Clube do Remo
  { clubCode: "4287", matches: 27, goals: 30, shotsSaved: 73, shotsOff: 146, shotsWoodwork: 5, tackles: 417, foulsCommitted: 302, yellowCards: 52, redCards: 4, saves: 105 },
  // Corinthians
  { clubCode: "1779", matches: 26, goals: 27, shotsSaved: 68, shotsOff: 139, shotsWoodwork: 4, tackles: 385, foulsCommitted: 354, yellowCards: 65, redCards: 4, saves: 71 },
  // Coritiba
  { clubCode: "4241", matches: 26, goals: 32, shotsSaved: 54, shotsOff: 116, shotsWoodwork: 6, tackles: 342, foulsCommitted: 274, yellowCards: 42, redCards: 7, saves: 93 },
  // Cruzeiro
  { clubCode: "1771", matches: 27, goals: 39, shotsSaved: 92, shotsOff: 158, shotsWoodwork: 3, tackles: 414, foulsCommitted: 376, yellowCards: 64, redCards: 3, saves: 72 },
  // Flamengo
  { clubCode: "1783", matches: 25, goals: 48, shotsSaved: 79, shotsOff: 150, shotsWoodwork: 14, tackles: 378, foulsCommitted: 288, yellowCards: 49, redCards: 6, saves: 67 },
  // Fluminense
  { clubCode: "1765", matches: 26, goals: 40, shotsSaved: 102, shotsOff: 149, shotsWoodwork: 11, tackles: 403, foulsCommitted: 339, yellowCards: 64, redCards: 1, saves: 97 },
  // Grêmio
  { clubCode: "1767", matches: 25, goals: 26, shotsSaved: 66, shotsOff: 114, shotsWoodwork: 5, tackles: 340, foulsCommitted: 328, yellowCards: 62, redCards: 4, saves: 75 },
  // Internacional
  { clubCode: "6684", matches: 27, goals: 29, shotsSaved: 89, shotsOff: 165, shotsWoodwork: 3, tackles: 391, foulsCommitted: 415, yellowCards: 63, redCards: 3, saves: 63 },
  // Mirassol
  { clubCode: "4364", matches: 24, goals: 24, shotsSaved: 79, shotsOff: 139, shotsWoodwork: 8, tackles: 358, foulsCommitted: 309, yellowCards: 66, redCards: 3, saves: 73 },
  // Palmeiras
  { clubCode: "1769", matches: 27, goals: 45, shotsSaved: 79, shotsOff: 154, shotsWoodwork: 8, tackles: 420, foulsCommitted: 374, yellowCards: 51, redCards: 4, saves: 83 },
  // Santos
  { clubCode: "6685", matches: 24, goals: 36, shotsSaved: 68, shotsOff: 144, shotsWoodwork: 6, tackles: 473, foulsCommitted: 319, yellowCards: 71, redCards: 4, saves: 63 },
  // São Paulo
  { clubCode: "1776", matches: 26, goals: 29, shotsSaved: 77, shotsOff: 135, shotsWoodwork: 5, tackles: 401, foulsCommitted: 376, yellowCards: 56, redCards: 2, saves: 69 },
  // Vasco da Gama
  { clubCode: "1780", matches: 25, goals: 29, shotsSaved: 97, shotsOff: 164, shotsWoodwork: 11, tackles: 388, foulsCommitted: 321, yellowCards: 55, redCards: 2, saves: 75 },
  // Vitória
  { clubCode: "1782", matches: 24, goals: 25, shotsSaved: 70, shotsOff: 121, shotsWoodwork: 4, tackles: 355, foulsCommitted: 318, yellowCards: 57, redCards: 3, saves: 83 },
];

/** The last rodada these counters cover. */
export const CLUB_SCOUTS_THROUGH_ROUND = 27;
