import type { ClubCode } from "@/src/types";

/**
 * Official sites the provider names **wrongly**, keyed by club code.
 *
 * The sibling of `coach-overrides.ts`, and it exists for the same reason: the
 * provider is the source, `clubs.ts` is generated by `sync-seed-data`, and a
 * hand-edit to that file is overwritten by the next run without a word.
 * Correcting at serve time survives the regeneration.
 *
 * **The bar is the one `coach-overrides.ts` sets, with one clause added that is
 * specific to an address: correct only where the recorded URL is no longer the
 * club's, and only where the right answer can be established by two independent
 * sources.** A site that merely redirects, restyles or moves to a new path stays
 * — `officialSiteUrl` stores an origin, so a path change is not a change here,
 * and a redirect is the provider's value still working.
 *
 * **A dead domain is not the failure worth guarding against; a RESOLD one is.**
 * A club's lapsed domain is worth money to whoever wants its inbound links, so
 * the shape to expect is a 200 serving somebody else's content rather than a
 * timeout — which is precisely the state that looks healthy to every automated
 * check short of reading the page. That is what happened below, and it is why
 * `scripts/check-club-websites.ts` asks whether the page still names the club
 * rather than whether it answers.
 *
 * Values are stored the way `sync-seed-data` normalises them — through
 * `officialSiteUrl`, so an **HTTPS origin with a trailing slash and no path**,
 * which is what `Club.website` is documented to hold. Storing a path would be
 * stripped in the club page's JSON-LD `sameAs` (`structured-data-core.ts` runs
 * the value through `officialSiteUrl`) while surviving in the rendered anchor,
 * so the page and its structured data would disagree about one address.
 */
export const CLUB_WEBSITE_OVERRIDES: Record<ClubCode, string> = {
  // Bragantino. Served as `https://www.bragantino.net/`, which **is no longer
  // the club's domain**: as of 2026-09-15 it serves a Vietnamese jobs blog
  // ("Kiếm việc làm trực tuyến tại TPHCM"), a WordPress install whose most
  // recent post is dated 2025-12-02, with no club content of any kind. Checked
  // in a real browser and by `curl` with a Chrome user agent — **identical
  // title, identical 118 414 bytes, so the domain is not cloaking**; every
  // occurrence of the string "bragantino" in the served HTML is the domain
  // inside its own permalinks, and there is no mention of Red Bull, Massa
  // Bruta, or any football whatever.
  //
  // The club's own site is Red Bull's. Three independent sources, none of them
  // naming bragantino.net:
  //   - the club's own X profile (@RedBullBraga, which this repo already
  //     records in `club-twitter.ts`) links `redbullbragantino.com/br-pt`;
  //   - pt.wikipedia's infobox: `| site = [https://www.redbullbragantino.com.br/`;
  //   - Wikidata's P856, ranked `preferred`: `https://www.redbullbragantino.com.br`.
  //
  // `www.redbullbragantino.com.br` is stored rather than the `/br-pt` address
  // the X bio uses, for the reason the header gives — this field holds an
  // origin — and because the `.com.br` name is the more durable of the two: it
  // 301s to `redbullbragantino.com`, which 302s to `/br-pt`, so a locale path
  // Red Bull reorganises tomorrow cannot rot the link while the Brazilian
  // domain keeps resolving. Verified 2026-09-15: the chain ends 200 on the
  // club's live site, carrying this season's Brasileirão fixtures.
  //
  // Note the repo had **already** concluded this club is Red Bull's everywhere
  // a human curated a value — `club-facebook.ts` (`RedBullBragantino`),
  // `club-twitter.ts` (`RedBullBraga`), `club-instagram.ts`
  // (`redbullbragantino`), `club-youtube.ts` (`MassaBrutaTV`) and
  // `club-wikipedia.ts` ("Red Bull Bragantino"). `website` is the one field on
  // this club nobody curates, which is exactly why it was the one left wrong.
  "4286": "https://www.redbullbragantino.com.br/",
};
