import type { Goal } from "@/src/types";

/**
 * GENERATED by scripts/sync-goals.ts — but safe to hand-edit.
 *
 * Who scored, per match. **No football-data tier this app can reach carries
 * goal events** — verified against a live Série A match and a live Premier
 * League one, both free, both answering with no `goals` key at all — so this
 * comes from CBF's own match endpoint, read on a workstation and never by the
 * running app. See `docs/data-sources.md`.
 *
 * Keyed by **our** match id, for the reason `broadcasts.ts` is: CBF's ids are
 * its own.
 *
 * **Every entry here has been reconciled against its own scoreline** — the
 * goals attributed to each club add up to that club's score, checked both
 * against CBF's reported score and against ours — and the sync refuses to write
 * one that does not. A missing match means "not synced, or did not reconcile",
 * never "goalless": a real 0-0 is deliberately absent rather than an empty
 * array, since the two would be indistinguishable here.
 *
 * Last synced 2026-08-31.
 */
export const GOALS: Record<string, Goal[]> = {
  "554740": [
    { clubCode: "1769", scorer: "Lopez", minute: "26'" },
    { clubCode: "1766", scorer: "Victor Hugo", minute: "44'" },
    { clubCode: "1766", scorer: "Khellven", kind: "own", minute: "73'" },
    { clubCode: "1769", scorer: "Vitor Roque", minute: "82'" },
  ],
  "554741": [
    { clubCode: "1770", scorer: "Danilo Santos", minute: "48'" },
    { clubCode: "1770", scorer: "Matheus Martins", minute: "75'" },
    { clubCode: "1770", scorer: "Danilo Santos", minute: "84'" },
    { clubCode: "1770", scorer: "Artur", minute: "90'" },
  ],
  "554742": [
    { clubCode: "1772", scorer: "Walter Clar", kind: "penalty", minute: "15'" },
    { clubCode: "6685", scorer: "Gabriel Menino", minute: "45+1'" },
    { clubCode: "6685", scorer: "Barreal", minute: "66'" },
    { clubCode: "1772", scorer: "Higor", minute: "73'" },
    { clubCode: "1772", scorer: "Jean Carlos", minute: "79'" },
    { clubCode: "1772", scorer: "Rafael Carvalheira", minute: "89'" },
  ],
  "554743": [
    { clubCode: "1779", scorer: "Bidon", minute: "12'" },
    { clubCode: "1777", scorer: "Jean Lucas", minute: "31'" },
    { clubCode: "1777", scorer: "Willian José", kind: "penalty", minute: "45'" },
  ],
  "554744": [
    { clubCode: "4286", scorer: "J. Capixaba", minute: "90+4'" },
  ],
  "554745": [
    { clubCode: "1765", scorer: "Nonato", minute: "46'" },
    { clubCode: "1765", scorer: "Lucho Acosta", minute: "59'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "74'" },
  ],
  "554746": [
    { clubCode: "1768", scorer: "Mendoza", minute: "9'" },
  ],
  "554747": [
    { clubCode: "1780", scorer: "Philippe Coutinho", minute: "21'" },
    { clubCode: "4364", scorer: "Cuesta", kind: "own", minute: "31'" },
    { clubCode: "4364", scorer: "Carlos", minute: "53'" },
  ],
  "554748": [
    { clubCode: "1783", scorer: "Plata", minute: "54'" },
    { clubCode: "1776", scorer: "Luciano", minute: "60'" },
    { clubCode: "1776", scorer: "Daniel", minute: "70'" },
  ],
  "554749": [
    { clubCode: "1782", scorer: "Renato Kayzer", minute: "57'" },
    { clubCode: "1782", scorer: "Gabriel Baralhas", minute: "76'" },
  ],
  "554750": [
    { clubCode: "1779", scorer: "Rodrigo Garro", minute: "20'" },
  ],
  "554751": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "19'" },
    { clubCode: "1777", scorer: "Kike Olivera", minute: "77'" },
  ],
  "554752": [
    { clubCode: "4286", scorer: "Gustavo Neves", minute: "37'" },
  ],
  "554753": [
    { clubCode: "1771", scorer: "Matheus Pereira", minute: "18'" },
    { clubCode: "4241", scorer: "Lavega", minute: "44'" },
    { clubCode: "4241", scorer: "Breno", minute: "52'" },
  ],
  "554754": [
    { clubCode: "6684", scorer: "Borre", minute: "45+2'" },
    { clubCode: "1783", scorer: "De Arrascaeta", kind: "penalty", minute: "68'" },
  ],
  "554755": [
    { clubCode: "1770", scorer: "Arthur", minute: "16'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "26'" },
    { clubCode: "1770", scorer: "Danilo Santos", minute: "35'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "50'" },
    { clubCode: "1767", scorer: "Vinicius", kind: "penalty", minute: "56'" },
    { clubCode: "1767", scorer: "Tete", minute: "59'" },
    { clubCode: "1767", scorer: "Edenilson", minute: "79'" },
    { clubCode: "1770", scorer: "Danilo Santos", minute: "85'" },
  ],
  "554756": [
    { clubCode: "1769", scorer: "Murilo", minute: "23'" },
    { clubCode: "1769", scorer: "Gustavo Gomez", minute: "28'" },
    { clubCode: "1769", scorer: "Mauricio", minute: "45+4'" },
    { clubCode: "1782", scorer: "Dudu", minute: "56'" },
    { clubCode: "1769", scorer: "Allan", minute: "62'" },
    { clubCode: "1769", scorer: "Ramon Sosa", minute: "79'" },
  ],
  "554757": [
    { clubCode: "4287", scorer: "João Pedro", minute: "8'" },
    { clubCode: "4287", scorer: "Alef Manga", minute: "39'" },
    { clubCode: "4364", scorer: "Igor", minute: "80'" },
    { clubCode: "4364", scorer: "Nathan Fogaca", minute: "88'" },
  ],
  "554758": [
    { clubCode: "6685", scorer: "Ze Rafael", minute: "45+4'" },
    { clubCode: "1776", scorer: "Calleri", minute: "65'" },
  ],
  "554759": [
    { clubCode: "1780", scorer: "Puma Rodriguez", minute: "54'" },
    { clubCode: "1772", scorer: "Jean Carlos", kind: "freekick", minute: "90'" },
  ],
  "554760": [
    { clubCode: "1768", scorer: "Julimar", kind: "penalty", minute: "5'" },
    { clubCode: "6685", scorer: "Thaciano", minute: "16'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "90'" },
  ],
  "554761": [
    { clubCode: "1766", scorer: "Hulk", minute: "21'" },
    { clubCode: "4287", scorer: "Vitor Bueno", minute: "42'" },
    { clubCode: "1766", scorer: "Ruan", minute: "69'" },
    { clubCode: "4287", scorer: "Yago", minute: "86'" },
    { clubCode: "4287", scorer: "Alef Manga", minute: "90+1'" },
    { clubCode: "1766", scorer: "Dudu", minute: "90+7'" },
  ],
  "554762": [
    { clubCode: "4241", scorer: "Breno", minute: "40'" },
    { clubCode: "1772", scorer: "Walter Clar", minute: "45'" },
    { clubCode: "4241", scorer: "Breno", minute: "57'" },
    { clubCode: "4241", scorer: "Pedro Rocha", minute: "58'" },
    { clubCode: "1772", scorer: "Edu Doma", minute: "71'" },
    { clubCode: "1772", scorer: "Rubens", minute: "90+1'" },
  ],
  "554763": [
    { clubCode: "1779", scorer: "Gabriel", minute: "46'" },
    { clubCode: "1779", scorer: "Matheus Bidu", minute: "74'" },
  ],
  "554764": [
    { clubCode: "1765", scorer: "Lucho Acosta", minute: "55'" },
  ],
  "554765": [
    { clubCode: "1769", scorer: "Gustavo Gomez", minute: "22'" },
    { clubCode: "6684", scorer: "Ronaldo", minute: "35'" },
    { clubCode: "1769", scorer: "Vitor Roque", minute: "51'" },
    { clubCode: "1769", scorer: "Andreas Pereira", minute: "82'" },
  ],
  "554766": [
    { clubCode: "1771", scorer: "Wanderson", minute: "22'" },
    { clubCode: "4364", scorer: "Nathan Fogaca", minute: "38'" },
    { clubCode: "4364", scorer: "Negueba", minute: "52'" },
    { clubCode: "1771", scorer: "Kaio Jorge", kind: "penalty", minute: "84'" },
  ],
  "554767": [
    { clubCode: "1776", scorer: "Lucas Moura", kind: "penalty", minute: "24'" },
    { clubCode: "1776", scorer: "Calleri", minute: "58'" },
  ],
  "554768": [
    { clubCode: "1777", scorer: "Luciano Juba", minute: "22'" },
  ],
  "554769": [
    { clubCode: "1783", scorer: "Erick Pulgar", minute: "14'" },
    { clubCode: "1783", scorer: "Everton", minute: "45+3'" },
    { clubCode: "1782", scorer: "Matheuzinho", minute: "51'" },
  ],
  "554772": [
    { clubCode: "4286", scorer: "J. Capixaba", kind: "freekick", minute: "43'" },
    { clubCode: "1768", scorer: "Julimar", minute: "79'" },
  ],
  "554773": [
    { clubCode: "1776", scorer: "Cauly", kind: "penalty", minute: "56'" },
  ],
  "554774": [
    { clubCode: "1771", scorer: "Matheus Pereira", minute: "8'" },
    { clubCode: "1779", scorer: "Joao Pedro", minute: "81'" },
  ],
  "554776": [
    { clubCode: "1767", scorer: "Erick Noriega", minute: "50'" },
    { clubCode: "1766", scorer: "Victor Hugo", minute: "56'" },
    { clubCode: "1767", scorer: "Marlon", minute: "67'" },
  ],
  "554777": [
    { clubCode: "1769", scorer: "Vitor Roque", kind: "penalty", minute: "9'" },
    { clubCode: "1769", scorer: "Allan", minute: "13'" },
    { clubCode: "1765", scorer: "Lucho Acosta", minute: "40'" },
  ],
  "554778": [
    { clubCode: "6684", scorer: "Alan Patrick", minute: "4'" },
    { clubCode: "4287", scorer: "Picco", minute: "13'" },
  ],
  "554779": [
    { clubCode: "6685", scorer: "Neymar Jr", minute: "24'" },
    { clubCode: "1780", scorer: "Barros", minute: "42'" },
    { clubCode: "6685", scorer: "Neymar Jr", minute: "61'" },
  ],
  "554780": [
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "3'" },
    { clubCode: "1770", scorer: "Edenilson", minute: "43'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "45+3'" },
    { clubCode: "1768", scorer: "Aguirre", minute: "49'" },
    { clubCode: "1768", scorer: "Lucas Esquivel", kind: "freekick", minute: "81'" },
  ],
  "554781": [
    { clubCode: "1766", scorer: "Cuello", minute: "2'" },
  ],
  "554782": [
    { clubCode: "1782", scorer: "Ramon", minute: "45+5'" },
    { clubCode: "1777", scorer: "Jean Lucas", minute: "45+1'" },
  ],
  "554783": [
    { clubCode: "4241", scorer: "Jacy", minute: "36'" },
    { clubCode: "4241", scorer: "Lucas Ronier", minute: "52'" },
  ],
  "554784": [
    { clubCode: "1783", scorer: "Pedro", minute: "5'" },
    { clubCode: "1783", scorer: "Carrascal", minute: "90+7'" },
  ],
  "554785": [
    { clubCode: "1767", scorer: "Vinicius", minute: "6'" },
    { clubCode: "4286", scorer: "Rodriguinho", minute: "65'" },
  ],
  "554786": [
    { clubCode: "4364", scorer: "Igor", minute: "20'" },
    { clubCode: "4364", scorer: "Negueba", minute: "70'" },
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "79'" },
    { clubCode: "6685", scorer: "Gabriel Barbosa", kind: "penalty", minute: "87'" },
  ],
  "554787": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "15'" },
    { clubCode: "1765", scorer: "Canobbio", minute: "62'" },
  ],
  "554788": [
    { clubCode: "1776", scorer: "Luciano", minute: "47'" },
    { clubCode: "1776", scorer: "Calleri", minute: "60'" },
  ],
  "554789": [
    { clubCode: "1769", scorer: "Lopez", minute: "40'" },
    { clubCode: "1780", scorer: "Thiago Mendes", minute: "62'" },
    { clubCode: "1780", scorer: "Cuiabano", minute: "73'" },
  ],
  "554790": [
    { clubCode: "1783", scorer: "Samuel Lino", minute: "12'" },
    { clubCode: "1783", scorer: "Leo Pereira", kind: "freekick", minute: "45+1'" },
    { clubCode: "1783", scorer: "Pedro", minute: "48'" },
  ],
  "554791": [
    { clubCode: "4286", scorer: "Herrera", minute: "36'" },
    { clubCode: "1776", scorer: "Sabino", minute: "52'" },
    { clubCode: "1776", scorer: "Calleri", minute: "68'" },
  ],
  "554792": [
    { clubCode: "1772", scorer: "Walter Clar", kind: "penalty", minute: "27'" },
    { clubCode: "1767", scorer: "Nardoni", minute: "45+3'" },
  ],
  "554793": [
    { clubCode: "4241", scorer: "Pedro Rocha", minute: "24'" },
  ],
  "554794": [
    { clubCode: "1771", scorer: "Christian", minute: "7'" },
    { clubCode: "1780", scorer: "Barros", minute: "51'" },
    { clubCode: "1780", scorer: "Barros", minute: "53'" },
    { clubCode: "1771", scorer: "Neiser", minute: "69'" },
    { clubCode: "1780", scorer: "Brenner", minute: "85'" },
    { clubCode: "1771", scorer: "Japa", minute: "90+4'" },
  ],
  "554795": [
    { clubCode: "1768", scorer: "Mendoza", minute: "4'" },
    { clubCode: "1765", scorer: "Hercules", minute: "9'" },
    { clubCode: "1765", scorer: "Canobbio", minute: "36'" },
    { clubCode: "1768", scorer: "Luiz Gustavo", minute: "73'" },
    { clubCode: "1765", scorer: "Guilherme Arana", minute: "90+3'" },
  ],
  "554796": [
    { clubCode: "1777", scorer: "Willian José", minute: "22'" },
  ],
  "554797": [
    { clubCode: "1769", scorer: "Lopez", minute: "25'" },
  ],
  "554798": [
    { clubCode: "1779", scorer: "Memphis Depay", minute: "17'" },
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "21'" },
  ],
  "554799": [
    { clubCode: "1782", scorer: "Renato Kayzer", kind: "freekick", minute: "20'" },
    { clubCode: "1782", scorer: "Erick", minute: "68'" },
  ],
  "554800": [
    { clubCode: "1768", scorer: "Mendoza", minute: "1'" },
    { clubCode: "1768", scorer: "Kevin Viveros", kind: "penalty", minute: "10'" },
    { clubCode: "1771", scorer: "Neiser", minute: "57'" },
  ],
  "554801": [
    { clubCode: "1766", scorer: "Roman Hurtado", minute: "64'" },
  ],
  "554802": [
    { clubCode: "1777", scorer: "Luciano Juba", minute: "17'" },
    { clubCode: "1777", scorer: "Erick", minute: "40'" },
  ],
  "554804": [
    { clubCode: "1783", scorer: "Léo Ortiz", minute: "19'" },
    { clubCode: "1783", scorer: "Samuel Lino", minute: "47'" },
    { clubCode: "1783", scorer: "Luiz", minute: "53'" },
  ],
  "554805": [
    { clubCode: "1767", scorer: "Camutanga", kind: "own", minute: "26'" },
    { clubCode: "1767", scorer: "Amuzu", minute: "53'" },
  ],
  "554806": [
    { clubCode: "4241", scorer: "Lavega", minute: "63'" },
  ],
  "554807": [
    { clubCode: "1769", scorer: "Allan", minute: "8'" },
    { clubCode: "1769", scorer: "Jhon Arias", minute: "52'" },
    { clubCode: "1770", scorer: "Danilo Santos", minute: "59'" },
  ],
  "554808": [
    { clubCode: "6684", scorer: "Ze Ivaldo", kind: "own", minute: "46'" },
    { clubCode: "6685", scorer: "Neymar Jr", kind: "penalty", minute: "56'" },
    { clubCode: "6684", scorer: "Carbonero", minute: "90+5'" },
  ],
  "554809": [
    { clubCode: "1765", scorer: "Canobbio", minute: "1'" },
    { clubCode: "1765", scorer: "Hercules", minute: "53'" },
    { clubCode: "1780", scorer: "Nuno", minute: "59'" },
    { clubCode: "1780", scorer: "Spinelli", minute: "88'" },
    { clubCode: "1780", scorer: "Thiago Mendes", minute: "90+5'" },
  ],
  "554810": [
    { clubCode: "1768", scorer: "Dudu", minute: "22'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "55'" },
  ],
  "554811": [
    { clubCode: "1770", scorer: "Alex Telles", kind: "penalty", minute: "7'" },
    { clubCode: "4286", scorer: "Lucas Barbosa", minute: "14'" },
    { clubCode: "1770", scorer: "Alexander Barboza", minute: "70'" },
  ],
  "554812": [
    { clubCode: "1783", scorer: "Lucas Paquetá", minute: "3'" },
    { clubCode: "1779", scorer: "Yuri Alberto", minute: "19'" },
  ],
  "554814": [
    { clubCode: "1765", scorer: "Castillo", minute: "29'" },
  ],
  "554815": [
    { clubCode: "6684", scorer: "Gabriel Mercado", minute: "28'" },
    { clubCode: "6684", scorer: "Alan Patrick", kind: "penalty", minute: "50'" },
  ],
  "554816": [
    { clubCode: "1777", scorer: "Everaldo", minute: "32'" },
    { clubCode: "4287", scorer: "Vitor Bueno", minute: "45+8'" },
    { clubCode: "4287", scorer: "Talairi", minute: "49'" },
    { clubCode: "4287", scorer: "Talairi", minute: "58'" },
    { clubCode: "4287", scorer: "Jajá", minute: "83'" },
  ],
  "554817": [
    { clubCode: "1769", scorer: "Jhon Arias", minute: "5'" },
  ],
  "554818": [
    { clubCode: "1780", scorer: "Thiago Mendes", minute: "7'" },
    { clubCode: "1780", scorer: "David", minute: "34'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "38'" },
  ],
  "554819": [
    { clubCode: "1782", scorer: "Gabriel Baralhas", minute: "27'" },
  ],
  "554820": [
    { clubCode: "1777", scorer: "Everaldo", minute: "3'" },
    { clubCode: "1777", scorer: "Everaldo", minute: "34'" },
    { clubCode: "1777", scorer: "Luciano Juba", minute: "90+2'" },
  ],
  "554821": [
    { clubCode: "1770", scorer: "Arthur", minute: "10'" },
    { clubCode: "4364", scorer: "Shaylon", minute: "20'" },
    { clubCode: "1770", scorer: "Alex Telles", kind: "penalty", minute: "42'" },
    { clubCode: "1770", scorer: "Junior", minute: "65'" },
    { clubCode: "4364", scorer: "Igor", minute: "90+2'" },
  ],
  "554822": [
    { clubCode: "4286", scorer: "Isidro Pitta", minute: "17'" },
    { clubCode: "4286", scorer: "Gabriel Girotto", minute: "38'" },
    { clubCode: "4286", scorer: "Lucas Barbosa", minute: "55'" },
  ],
  "554823": [
    { clubCode: "1766", scorer: "Bernard", minute: "23'" },
    { clubCode: "1766", scorer: "Reinier", minute: "29'" },
    { clubCode: "1766", scorer: "Cuello", minute: "34'" },
    { clubCode: "1766", scorer: "Dudu", minute: "90+4'" },
  ],
  "554824": [
    { clubCode: "1780", scorer: "Tche Tche", minute: "23'" },
    { clubCode: "4241", scorer: "Alan", kind: "own", minute: "90'" },
  ],
  "554825": [
    { clubCode: "1771", scorer: "Christian", minute: "32'" },
    { clubCode: "1771", scorer: "Kauã Moraes", minute: "35'" },
    { clubCode: "1771", scorer: "Kaio Jorge", minute: "39'" },
  ],
  "554826": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "19'" },
    { clubCode: "1765", scorer: "Hercules", minute: "45+2'" },
    { clubCode: "1765", scorer: "Castillo", minute: "82'" },
    { clubCode: "1779", scorer: "André", minute: "89'" },
  ],
  "554827": [
    { clubCode: "6684", scorer: "Alerrandro", minute: "23'" },
    { clubCode: "1776", scorer: "Calleri", minute: "87'" },
  ],
  "554828": [
    { clubCode: "1769", scorer: "Marlon Freitas", minute: "43'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "53'" },
    { clubCode: "1769", scorer: "Marlon Freitas", minute: "73'" },
  ],
  "554829": [
    { clubCode: "6685", scorer: "Thaciano", minute: "39'" },
    { clubCode: "6685", scorer: "Moises", minute: "81'" },
  ],
  "554830": [
    { clubCode: "1766", scorer: "Victor Hugo", minute: "6'" },
    { clubCode: "1766", scorer: "Gustavo Scarpa", minute: "80'" },
    { clubCode: "1768", scorer: "Julimar", minute: "88'" },
  ],
  "554831": [
    { clubCode: "1769", scorer: "Jhon Arias", minute: "23'" },
    { clubCode: "1777", scorer: "David Duarte", minute: "58'" },
    { clubCode: "1769", scorer: "Ramos Mingo", kind: "own", minute: "88'" },
  ],
  "554832": [
    { clubCode: "1772", scorer: "Neto", minute: "86'" },
    { clubCode: "1782", scorer: "Matheuzinho", kind: "penalty", minute: "90+2'" },
  ],
  "554833": [
    { clubCode: "6684", scorer: "Bernabei", minute: "78'" },
  ],
  "554834": [
    { clubCode: "4241", scorer: "Tiago Coser", minute: "73'" },
    { clubCode: "1765", scorer: "John Kennedy", minute: "80'" },
  ],
  "554835": [
    { clubCode: "6685", scorer: "Lautaro", minute: "47'" },
    { clubCode: "1783", scorer: "Pedro", minute: "63'" },
    { clubCode: "1783", scorer: "Jorge", kind: "penalty", minute: "71'" },
    { clubCode: "1783", scorer: "Lucas Paquetá", minute: "89'" },
  ],
  "554837": [
    { clubCode: "4286", scorer: "Isidro Pitta", minute: "50'" },
  ],
  "554838": [
    { clubCode: "1776", scorer: "Calleri", kind: "penalty", minute: "12'" },
    { clubCode: "1776", scorer: "Ferreira", minute: "16'" },
    { clubCode: "1771", scorer: "Christian", minute: "47'" },
    { clubCode: "1776", scorer: "Ferreira", minute: "62'" },
    { clubCode: "1776", scorer: "Ferreira", minute: "90+1'" },
  ],
  "554839": [
    { clubCode: "1780", scorer: "David", minute: "61'" },
    { clubCode: "1770", scorer: "Lucas Villalba", minute: "65'" },
    { clubCode: "1770", scorer: "Matheus Martins", minute: "78'" },
  ],
  "554840": [
    { clubCode: "1768", scorer: "Mendoza", minute: "57'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "80'" },
  ],
  "554841": [
    { clubCode: "4241", scorer: "Breno", minute: "32'" },
    { clubCode: "1770", scorer: "Danilo Santos", minute: "54'" },
    { clubCode: "1770", scorer: "Arthur", minute: "77'" },
    { clubCode: "4241", scorer: "Lavega", minute: "79'" },
  ],
  "554843": [
    { clubCode: "4286", scorer: "Andres Hurtado", minute: "5'" },
    { clubCode: "1771", scorer: "Neiser", minute: "18'" },
    { clubCode: "1771", scorer: "Christian", minute: "49'" },
  ],
  "554844": [
    { clubCode: "1783", scorer: "Pedro", minute: "7'" },
    { clubCode: "1783", scorer: "Pedro", minute: "50'" },
    { clubCode: "1765", scorer: "Savarino", minute: "76'" },
  ],
  "554846": [
    { clubCode: "4364", scorer: "David Duarte", kind: "own", minute: "13'" },
    { clubCode: "1777", scorer: "Luciano Juba", kind: "penalty", minute: "64'" },
    { clubCode: "1777", scorer: "Sanabria", minute: "88'" },
  ],
  "554847": [
    { clubCode: "1780", scorer: "Hinestroza", minute: "54'" },
    { clubCode: "4287", scorer: "Marllon", minute: "83'" },
  ],
  "554848": [
    { clubCode: "6685", scorer: "Moises", minute: "63'" },
  ],
  "554849": [
    { clubCode: "1782", scorer: "Cacá", minute: "35'" },
    { clubCode: "1782", scorer: "Ramon", minute: "83'" },
  ],
  "554850": [
    { clubCode: "4286", scorer: "Isidro Pitta", minute: "19'" },
    { clubCode: "4287", scorer: "Talairi", minute: "27'" },
    { clubCode: "4286", scorer: "Isidro Pitta", minute: "37'" },
    { clubCode: "4287", scorer: "Marcelinho", minute: "38'" },
    { clubCode: "4286", scorer: "Tchamba", kind: "own", minute: "47'" },
    { clubCode: "4286", scorer: "Tchamba", kind: "own", minute: "51'" },
  ],
  "554851": [
    { clubCode: "1770", scorer: "Edenilson", minute: "10'" },
    { clubCode: "1770", scorer: "Matheus Martins", minute: "14'" },
    { clubCode: "1770", scorer: "Edenilson", minute: "20'" },
    { clubCode: "1772", scorer: "Marcinho", minute: "45+2'" },
    { clubCode: "1770", scorer: "Matheus Martins", minute: "79'" },
  ],
  "554852": [
    { clubCode: "4241", scorer: "Breno", minute: "7'" },
    { clubCode: "4241", scorer: "Pedro Rocha", minute: "58'" },
  ],
  "554853": [
    { clubCode: "1771", scorer: "Christian", minute: "51'" },
    { clubCode: "1771", scorer: "Lucas Romero", minute: "66'" },
  ],
  "554854": [
    { clubCode: "1783", scorer: "De Arrascaeta", minute: "16'" },
    { clubCode: "1783", scorer: "Lucas Paquetá", minute: "79'" },
  ],
  "554855": [
    { clubCode: "4364", scorer: "Lucas Oliveira", minute: "21'" },
    { clubCode: "4364", scorer: "Andre Luis", minute: "45'" },
    { clubCode: "6684", scorer: "Alan Patrick", minute: "90+2'" },
  ],
  "554856": [
    { clubCode: "1769", scorer: "Gustavo Gomez" },
  ],
  "554857": [
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "10'" },
    { clubCode: "1765", scorer: "Savarino", minute: "23'" },
    { clubCode: "6685", scorer: "Barreal", minute: "56'" },
    { clubCode: "1765", scorer: "Castillo", minute: "59'" },
    { clubCode: "1765", scorer: "John Kennedy", minute: "85'" },
  ],
  "554858": [
    { clubCode: "1776", scorer: "Luciano", minute: "10'" },
    { clubCode: "1780", scorer: "Puma Rodriguez", kind: "penalty", minute: "71'" },
    { clubCode: "1780", scorer: "Hinestroza", minute: "88'" },
  ],
  "554860": [
    { clubCode: "1782", scorer: "Rene", minute: "21'" },
    { clubCode: "1768", scorer: "Kevin Viveros", kind: "penalty", minute: "33'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "90+1'" },
    { clubCode: "1768", scorer: "Luiz Gustavo", minute: "90+7'" },
  ],
  "554861": [
    { clubCode: "1783", scorer: "Pedro", minute: "7'" },
    { clubCode: "1783", scorer: "Plata", minute: "30'" },
    { clubCode: "1783", scorer: "De Arrascaeta", minute: "45'" },
    { clubCode: "1783", scorer: "Pedro", minute: "84'" },
  ],
  "554862": [
    { clubCode: "6685", scorer: "Rollheiser", kind: "penalty", minute: "21'" },
    { clubCode: "6685", scorer: "Rollheiser", kind: "penalty", minute: "45+3'" },
    { clubCode: "1777", scorer: "Luciano Juba", kind: "freekick", minute: "76'" },
    { clubCode: "1777", scorer: "Willian José", minute: "83'" },
  ],
  "554863": [
    { clubCode: "1770", scorer: "Danilo Santos", minute: "53'" },
    { clubCode: "6684", scorer: "Carbonero", minute: "58'" },
    { clubCode: "1770", scorer: "Cristian Medina", minute: "65'" },
    { clubCode: "6684", scorer: "Bernabei", minute: "73'" },
  ],
  "554864": [
    { clubCode: "1769", scorer: "Lopez", minute: "20'" },
  ],
  "554865": [
    { clubCode: "1779", scorer: "Matheus Bidu", minute: "38'" },
  ],
  "554866": [
    { clubCode: "1765", scorer: "Savarino", kind: "penalty", minute: "55'" },
    { clubCode: "1772", scorer: "Enio", minute: "77'" },
    { clubCode: "1765", scorer: "John Kennedy", minute: "85'" },
  ],
  "554867": [
    { clubCode: "1767", scorer: "Gabriel Mec", minute: "42'" },
  ],
  "554868": [
    { clubCode: "1771", scorer: "Arroyo", minute: "33'" },
  ],
  "554869": [
    { clubCode: "1776", scorer: "Luciano", minute: "76'" },
  ],
  "554871": [
    { clubCode: "1770", scorer: "Ferraresi", minute: "13'" },
    { clubCode: "4287", scorer: "Alef Manga", minute: "69'" },
    { clubCode: "4287", scorer: "Jajá", minute: "90+1'" },
  ],
  "554872": [
    { clubCode: "1772", scorer: "Bolasie", minute: "22'" },
    { clubCode: "4286", scorer: "Gabriel Girotto", minute: "40'" },
    { clubCode: "4286", scorer: "Lucas Barbosa", minute: "72'" },
  ],
  "554873": [
    { clubCode: "1766", scorer: "Alan Minda", minute: "11'" },
    { clubCode: "1766", scorer: "Maycon", kind: "penalty", minute: "30'" },
    { clubCode: "1766", scorer: "Cassierra", minute: "70'" },
    { clubCode: "1771", scorer: "Kaio Jorge", kind: "penalty", minute: "85'" },
  ],
  "554874": [
    { clubCode: "1783", scorer: "Pedro", minute: "9'" },
    { clubCode: "1783", scorer: "Jorge", kind: "penalty", minute: "60'" },
    { clubCode: "1780", scorer: "Robert Renan", minute: "83'" },
    { clubCode: "1780", scorer: "Hugo Moura", minute: "90+6'" },
  ],
  "554875": [
    { clubCode: "6684", scorer: "Bernabei", minute: "38'" },
    { clubCode: "6684", scorer: "Alerrandro", minute: "48'" },
  ],
  "554876": [
    { clubCode: "4364", scorer: "Carlos Eduardo", kind: "penalty", minute: "22'" },
    { clubCode: "4364", scorer: "Edson Carioca", minute: "33'" },
    { clubCode: "1779", scorer: "Dieguinho", minute: "79'" },
  ],
  "554877": [
    { clubCode: "6685", scorer: "Rollheiser", minute: "26'" },
    { clubCode: "1769", scorer: "Lopez", minute: "63'" },
  ],
  "554878": [
    { clubCode: "1776", scorer: "Artur", minute: "17'" },
    { clubCode: "1777", scorer: "Luciano Juba", minute: "61'" },
    { clubCode: "1776", scorer: "Ferreira", minute: "72'" },
    { clubCode: "1777", scorer: "Erick", minute: "90+7'" },
  ],
  "554879": [
    { clubCode: "1782", scorer: "Rene", minute: "15'" },
    { clubCode: "1782", scorer: "Zé Vitor", minute: "28'" },
    { clubCode: "4241", scorer: "Pedro Rocha", minute: "45+2'" },
    { clubCode: "1782", scorer: "Diego Tarzia", minute: "55'" },
    { clubCode: "1782", scorer: "Erick", kind: "penalty", minute: "60'" },
  ],
  "554880": [
    { clubCode: "1766", scorer: "Cassierra", minute: "22'" },
    { clubCode: "1770", scorer: "Arthur", minute: "89'" },
  ],
  "554881": [
    { clubCode: "1777", scorer: "Luciano Juba", kind: "penalty", minute: "26'" },
    { clubCode: "1771", scorer: "Kauã Moraes", minute: "41'" },
    { clubCode: "1771", scorer: "Kaique Kenji", minute: "85'" },
  ],
  "554882": [
    { clubCode: "1779", scorer: "Raniele", minute: "16'" },
    { clubCode: "1776", scorer: "Luciano", minute: "40'" },
    { clubCode: "1779", scorer: "Matheuzinho", minute: "51'" },
    { clubCode: "1779", scorer: "Bidon", minute: "57'" },
    { clubCode: "1776", scorer: "Matheuzinho", kind: "own", minute: "88'" },
  ],
  "554883": [
    { clubCode: "4241", scorer: "Lavega", minute: "28'" },
    { clubCode: "6684", scorer: "Borre", minute: "68'" },
    { clubCode: "4241", scorer: "Rodrigo Moledo", minute: "83'" },
    { clubCode: "6684", scorer: "Felix Torres", minute: "90+5'" },
  ],
  "554884": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "35'" },
    { clubCode: "1782", scorer: "Renato Kayzer", kind: "penalty", minute: "62'" },
    { clubCode: "1782", scorer: "Rene", minute: "67'" },
    { clubCode: "1765", scorer: "Kevin Serna", minute: "90'" },
  ],
  "554885": [
    { clubCode: "1783", scorer: "Carrascal", minute: "67'" },
  ],
  "554886": [
    { clubCode: "4364", scorer: "Carlos", minute: "70'" },
    { clubCode: "1772", scorer: "Carroll", kind: "own", minute: "80'" },
  ],
  "554888": [
    { clubCode: "6685", scorer: "Neymar Jr", minute: "45+4'" },
    { clubCode: "6685", scorer: "Adonis Frías", minute: "76'" },
  ],
  "554889": [
    { clubCode: "1780", scorer: "Thiago Mendes", minute: "36'" },
  ],
  "554890": [
    { clubCode: "1768", scorer: "Mendoza", minute: "10'" },
    { clubCode: "1783", scorer: "Pedro", minute: "83'" },
  ],
  "554891": [
    { clubCode: "1766", scorer: "Alan Minda", minute: "16'" },
    { clubCode: "4364", scorer: "Willian Machado", minute: "39'" },
    { clubCode: "1766", scorer: "Maycon", kind: "penalty", minute: "60'" },
    { clubCode: "1766", scorer: "Cisse", minute: "81'" },
  ],
  "554892": [
    { clubCode: "1767", scorer: "Viery", minute: "61'" },
    { clubCode: "1777", scorer: "Sanabria", minute: "72'" },
  ],
  "554893": [
    { clubCode: "1770", scorer: "Arthur", minute: "6'" },
    { clubCode: "1779", scorer: "Rodrigo Garro", minute: "11'" },
    { clubCode: "1770", scorer: "Arthur", minute: "31'" },
    { clubCode: "1770", scorer: "Arthur", minute: "70'" },
  ],
  "554894": [
    { clubCode: "4286", scorer: "Tiago Volpi", kind: "penalty", minute: "40'" },
    { clubCode: "4286", scorer: "Lucas Barbosa", minute: "90+9'" },
  ],
  "554895": [
    { clubCode: "4287", scorer: "Yago", minute: "16'" },
    { clubCode: "1772", scorer: "Neto", minute: "24'" },
    { clubCode: "1772", scorer: "Rafael Carvalheira", minute: "46'" },
    { clubCode: "4287", scorer: "Jajá", minute: "50'" },
    { clubCode: "4287", scorer: "Bruno Leonardo", kind: "own", minute: "86'" },
  ],
  "554896": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "19'" },
    { clubCode: "1765", scorer: "Canobbio", minute: "44'" },
    { clubCode: "1776", scorer: "Matheus", minute: "78'" },
  ],
  "554897": [
    { clubCode: "6684", scorer: "Carbonero", minute: "20'" },
    { clubCode: "6684", scorer: "Alerrandro", minute: "24'" },
    { clubCode: "6684", scorer: "Bernabei", minute: "62'" },
    { clubCode: "6684", scorer: "Carbonero", minute: "71'" },
    { clubCode: "1780", scorer: "Hinestroza", minute: "85'" },
  ],
  "554898": [
    { clubCode: "1771", scorer: "Arroyo", minute: "10'" },
    { clubCode: "1769", scorer: "Felipe Anderson", minute: "20'" },
  ],
  "554899": [
    { clubCode: "4241", scorer: "Breno", minute: "5'" },
    { clubCode: "4241", scorer: "Breno", minute: "20'" },
    { clubCode: "4241", scorer: "Josue", kind: "penalty", minute: "39'" },
  ],
  "554900": [
    { clubCode: "1779", scorer: "Zakaria", minute: "88'" },
  ],
  "554901": [
    { clubCode: "1777", scorer: "Erick Pulga", minute: "26'" },
    { clubCode: "4241", scorer: "Bruno Melo", minute: "55'" },
    { clubCode: "4241", scorer: "Lavega", minute: "64'" },
    { clubCode: "4241", scorer: "Breno", minute: "69'" },
    { clubCode: "1777", scorer: "Everaldo", minute: "90'" },
  ],
  "554902": [
    { clubCode: "1771", scorer: "Kaio Jorge", kind: "penalty", minute: "26'" },
    { clubCode: "1771", scorer: "Sinisterra", minute: "72'" },
    { clubCode: "1772", scorer: "João Paulo", minute: "79'" },
  ],
  "554903": [
    { clubCode: "1769", scorer: "Lopez", minute: "38'" },
    { clubCode: "1769", scorer: "Allan", minute: "56'" },
    { clubCode: "1769", scorer: "Paulinho", minute: "90+4'" },
  ],
  "554904": [
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "32'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "39'" },
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "54'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "58'" },
    { clubCode: "1767", scorer: "Tete", minute: "63'" },
  ],
  "554905": [
    { clubCode: "4364", scorer: "Denilson", minute: "36'" },
  ],
  "554906": [
    { clubCode: "4287", scorer: "Jajá", minute: "13'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "45'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "52'" },
  ],
  "554907": [
    { clubCode: "1776", scorer: "Luciano", minute: "4'" },
    { clubCode: "1770", scorer: "Jordan Barrera", minute: "90'" },
  ],
  "554908": [
    { clubCode: "4286", scorer: "Rodriguinho", minute: "45'" },
    { clubCode: "4286", scorer: "Isidro Pitta", minute: "59'" },
    { clubCode: "4286", scorer: "Fernando", minute: "76'" },
  ],
  "554909": [
    { clubCode: "1782", scorer: "Rene", minute: "28'" },
    { clubCode: "1782", scorer: "Diego Tarzia", minute: "90+6'" },
  ],
  "554910": [
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "88'" },
  ],
  "554911": [
    { clubCode: "1770", scorer: "Huguinho", minute: "6'" },
    { clubCode: "1777", scorer: "Ferraresi", kind: "own", minute: "56'" },
    { clubCode: "1777", scorer: "David Duarte", minute: "90'" },
  ],
  "554912": [
    { clubCode: "4286", scorer: "Fernando", minute: "18'" },
    { clubCode: "4286", scorer: "J. Capixaba", kind: "freekick", minute: "45+6'" },
    { clubCode: "4286", scorer: "Tiago Volpi", kind: "penalty", minute: "51'" },
    { clubCode: "6684", scorer: "Braian Aguirre", minute: "78'" },
  ],
  "554913": [
    { clubCode: "1765", scorer: "John Kennedy", minute: "42'" },
    { clubCode: "1771", scorer: "Matheus Pereira", kind: "freekick", minute: "75'" },
  ],
  "554914": [
    { clubCode: "1783", scorer: "Samuel Lino", minute: "10'" },
    { clubCode: "1783", scorer: "Pedro", minute: "59'" },
    { clubCode: "1783", scorer: "Samuel Lino", minute: "69'" },
  ],
  "554915": [
    { clubCode: "1767", scorer: "Gabriel Mec", minute: "8'" },
    { clubCode: "1779", scorer: "André", minute: "45+2'" },
    { clubCode: "1779", scorer: "André", minute: "65'" },
    { clubCode: "1779", scorer: "Kaio Lima", minute: "67'" },
  ],
  "554916": [
    { clubCode: "1769", scorer: "Paulinho", minute: "65'" },
  ],
  "554917": [
    { clubCode: "4287", scorer: "Marcelinho", minute: "90+3'" },
  ],
  "554918": [
    { clubCode: "6685", scorer: "Miguelito", minute: "18'" },
    { clubCode: "6685", scorer: "Barreal", minute: "54'" },
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "56'" },
    { clubCode: "1782", scorer: "Rene", minute: "74'" },
  ],
  "554919": [
    { clubCode: "1766", scorer: "Vitor Hugo", minute: "32'" },
  ],
  "554920": [
    { clubCode: "1766", scorer: "Ruan", minute: "45'" },
    { clubCode: "1777", scorer: "Ademir", minute: "56'" },
  ],
  "554921": [
    { clubCode: "1770", scorer: "Lucas", minute: "41'" },
    { clubCode: "6685", scorer: "Barreal", minute: "56'" },
    { clubCode: "1770", scorer: "Jose Kadir", minute: "90+4'" },
  ],
  "554922": [
    { clubCode: "1783", scorer: "Pedro", minute: "26'" },
    { clubCode: "1783", scorer: "R. Thyere", kind: "own", minute: "37'" },
    { clubCode: "1783", scorer: "Lorran", minute: "47'" },
    { clubCode: "1783", scorer: "Pedro", minute: "86'" },
  ],
  "554923": [
    { clubCode: "1779", scorer: "Yuri Alberto", minute: "26'" },
    { clubCode: "1779", scorer: "Kaio Lima", minute: "39'" },
    { clubCode: "1779", scorer: "Yuri Alberto", minute: "45+1'" },
  ],
  "554924": [
    { clubCode: "1769", scorer: "Mauricio", minute: "8'" },
    { clubCode: "1769", scorer: "Mauricio", minute: "18'" },
    { clubCode: "1769", scorer: "Ramon Sosa", minute: "66'" },
    { clubCode: "4241", scorer: "Paulo Roberto", minute: "67'" },
  ],
  "554925": [
    { clubCode: "4286", scorer: "Sasha", minute: "27'" },
    { clubCode: "1765", scorer: "Ignacio", minute: "90+13'" },
  ],
  "554926": [
    { clubCode: "1771", scorer: "Kaio Jorge", minute: "10'" },
    { clubCode: "1771", scorer: "Matheus Pereira", minute: "64'" },
    { clubCode: "6684", scorer: "Carbonero", minute: "82'" },
  ],
  "554927": [
    { clubCode: "4364", scorer: "Bruno Santos", minute: "15'" },
    { clubCode: "4364", scorer: "Edson Carioca", minute: "39'" },
    { clubCode: "1767", scorer: "Vinicius", minute: "77'" },
  ],
  "554928": [
    { clubCode: "1776", scorer: "Artur", kind: "freekick", minute: "18'" },
    { clubCode: "1768", scorer: "Leozinho", minute: "46'" },
    { clubCode: "1768", scorer: "Leozinho", minute: "51'" },
  ],
  "554929": [
    { clubCode: "1782", scorer: "Renato Kayzer", minute: "69'" },
  ],
  "554930": [
    { clubCode: "1768", scorer: "Leozinho", minute: "45+1'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "59'" },
  ],
  "554931": [
    { clubCode: "1779", scorer: "Fabrizio Angileri", minute: "7'" },
    { clubCode: "1777", scorer: "David Duarte", minute: "45+3'" },
  ],
  "554933": [
    { clubCode: "1770", scorer: "Gabriel", minute: "40'" },
  ],
  "554934": [
    { clubCode: "1783", scorer: "Leo Pereira", minute: "56'" },
    { clubCode: "1776", scorer: "Calleri", minute: "70'" },
  ],
  "554935": [
    { clubCode: "1765", scorer: "Hulk", kind: "penalty", minute: "64'" },
    { clubCode: "1767", scorer: "Diego Caito", minute: "88'" },
  ],
  "554936": [
    { clubCode: "1766", scorer: "Victor Hugo", minute: "53'" },
    { clubCode: "1769", scorer: "Felipe Anderson", minute: "74'" },
    { clubCode: "1766", scorer: "Igor Gomes", minute: "76'" },
  ],
  "554937": [
    { clubCode: "4287", scorer: "Ze Ivaldo", minute: "38'" },
    { clubCode: "4287", scorer: "Alef Manga", minute: "54'" },
  ],
  "554938": [
    { clubCode: "6685", scorer: "Neymar Jr", minute: "35'" },
    { clubCode: "1772", scorer: "Marcinho", minute: "50'" },
    { clubCode: "1772", scorer: "João Ananias", kind: "own", minute: "62'" },
    { clubCode: "6685", scorer: "Neymar Jr", kind: "penalty", minute: "90'" },
  ],
  "554939": [
    { clubCode: "4364", scorer: "Igor", minute: "29'" },
    { clubCode: "1780", scorer: "Hinestroza", minute: "79'" },
  ],
  "554944": [
    { clubCode: "1771", scorer: "Matheus Pereira", minute: "65'" },
  ],
  "554946": [
    { clubCode: "6684", scorer: "Vitinho", minute: "26'" },
    { clubCode: "1783", scorer: "Samuel Lino", minute: "79'" },
  ],
  "554947": [
    { clubCode: "4364", scorer: "Marllon", kind: "own", minute: "30'" },
    { clubCode: "4287", scorer: "Picco", minute: "45'" },
    { clubCode: "4364", scorer: "Carroll", minute: "53'" },
  ],
  "554949": [
    { clubCode: "1769", scorer: "Mauricio", minute: "45+5'" },
    { clubCode: "1769", scorer: "Fabiano Josue de Souza Silva", kind: "own", minute: "45'" },
    { clubCode: "1769", scorer: "Jhon Arias", minute: "69'" },
    { clubCode: "1769", scorer: "Ramon Sosa", kind: "freekick", minute: "83'" },
  ],
  "554951": [
    { clubCode: "1770", scorer: "Alex Telles", kind: "freekick", minute: "43'" },
    { clubCode: "1765", scorer: "Ignacio", minute: "58'" },
  ],
  "554952": [
    { clubCode: "1779", scorer: "Rodrigo Garro", minute: "58'" },
    { clubCode: "1779", scorer: "Pedro Raul", minute: "86'" },
  ],
  "554953": [
    { clubCode: "4241", scorer: "Tiago Coser", minute: "30'" },
    { clubCode: "4241", scorer: "Pedro Rocha", minute: "82'" },
    { clubCode: "1772", scorer: "Tulio Oliveira", minute: "90+5'" },
  ],
  "554954": [
    { clubCode: "1771", scorer: "Joao Marcelo", minute: "12'" },
    { clubCode: "4364", scorer: "Reinaldo", kind: "penalty", minute: "26'" },
    { clubCode: "1771", scorer: "Kaio Jorge", minute: "76'" },
    { clubCode: "1771", scorer: "Wesley", minute: "83'" },
  ],
  "554955": [
    { clubCode: "1783", scorer: "Erick Pulgar", minute: "13'" },
    { clubCode: "1783", scorer: "Bruno Henrique", minute: "79'" },
  ],
  "554956": [
    { clubCode: "1776", scorer: "G. Martins", kind: "own", minute: "45+2'" },
    { clubCode: "1767", scorer: "Wallace", minute: "47'" },
    { clubCode: "1767", scorer: "Pavon", minute: "85'" },
  ],
  "554958": [
    { clubCode: "4287", scorer: "Jajá", minute: "3'" },
    { clubCode: "1766", scorer: "Reinier", minute: "34'" },
    { clubCode: "1766", scorer: "Bernard", minute: "38'" },
    { clubCode: "4287", scorer: "Talairi", minute: "73'" },
  ],
  "554959": [
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "14'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "25'" },
  ],
  "554960": [
    { clubCode: "4286", scorer: "Pedro Henrique", minute: "67'" },
    { clubCode: "1768", scorer: "Kerwin Vargas", minute: "74'" },
  ],
  "554961": [
    { clubCode: "1766", scorer: "Vitor Hugo", minute: "19'" },
    { clubCode: "1766", scorer: "Cuello", minute: "61'" },
    { clubCode: "1766", scorer: "Cuello", minute: "65'" },
  ],
  "554962": [
    { clubCode: "1777", scorer: "Alejo", kind: "penalty", minute: "13'" },
    { clubCode: "1772", scorer: "Giovanni Augusto", minute: "20'" },
    { clubCode: "1777", scorer: "Kauan", kind: "own", minute: "43'" },
    { clubCode: "1772", scorer: "Marcinho", minute: "48'" },
    { clubCode: "1777", scorer: "Acevedo", minute: "65'" },
    { clubCode: "1772", scorer: "Tulio Oliveira", minute: "71'" },
  ],
  "554963": [
    { clubCode: "1771", scorer: "Bruno Rodrigues", minute: "35'" },
    { clubCode: "1779", scorer: "Gustavo", minute: "57'" },
    { clubCode: "1771", scorer: "Wanderson", minute: "81'" },
  ],
  "554964": [
    { clubCode: "1769", scorer: "Gustavo Gomez", minute: "10'" },
    { clubCode: "1765", scorer: "Hulk", minute: "42'" },
    { clubCode: "1769", scorer: "Mauricio", minute: "82'" },
    { clubCode: "1765", scorer: "Kevin Serna", minute: "85'" },
    { clubCode: "1765", scorer: "German Cano", minute: "90+2'" },
  ],
  "554965": [
    { clubCode: "6684", scorer: "Carbonero", minute: "3'" },
    { clubCode: "4287", scorer: "Vitor Bueno", kind: "freekick", minute: "90+4'" },
  ],
  "554966": [
    { clubCode: "1783", scorer: "Carrascal", minute: "22'" },
    { clubCode: "1783", scorer: "Luiz", minute: "52'" },
    { clubCode: "1783", scorer: "Pedro", minute: "55'" },
    { clubCode: "1783", scorer: "Pedro", minute: "65'" },
    { clubCode: "1783", scorer: "Samuel Lino", minute: "73'" },
    { clubCode: "4364", scorer: "Carroll", minute: "76'" },
  ],
  "554967": [
    { clubCode: "1776", scorer: "Pablo Maia", minute: "42'" },
    { clubCode: "4241", scorer: "Tiago Coser", minute: "57'" },
  ],
  "554968": [
    { clubCode: "6685", scorer: "Gabriel Barbosa", minute: "67'" },
    { clubCode: "6685", scorer: "Willian Arao", minute: "76'" },
    { clubCode: "6685", scorer: "Luan Peres", minute: "81'" },
  ],
  "554969": [
    { clubCode: "1782", scorer: "Matheuzinho", kind: "penalty", minute: "26'" },
  ],
  "554970": [
    { clubCode: "1768", scorer: "João Cruz", minute: "10'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "13'" },
    { clubCode: "1768", scorer: "Kevin Viveros", minute: "78'" },
    { clubCode: "1770", scorer: "Santiago", minute: "84'" },
    { clubCode: "1770", scorer: "Santiago", minute: "90+2'" },
  ],
  "554971": [
    { clubCode: "4286", scorer: "Gustavo Marques", minute: "90+4'" },
  ],
  "554972": [
    { clubCode: "1772", scorer: "Bruno Pacheco", minute: "26'" },
  ],
  "554973": [
    { clubCode: "4241", scorer: "Pedro Rocha" },
    { clubCode: "4241", scorer: "Paulo Roberto" },
    { clubCode: "1779", scorer: "Raniele" },
  ],
  "554974": [
    { clubCode: "1783", scorer: "Pedro", minute: "21'" },
    { clubCode: "1771", scorer: "Arroyo", minute: "54'" },
    { clubCode: "1771", scorer: "Matheus Pereira", minute: "90+4'" },
  ],
  "554975": [
    { clubCode: "4287", scorer: "Jajá", minute: "31'" },
    { clubCode: "1765", scorer: "Hulk", minute: "66'" },
    { clubCode: "1765", scorer: "Kevin Serna", minute: "82'" },
  ],
  "554977": [
    { clubCode: "1769", scorer: "Lopez", minute: "46'" },
    { clubCode: "1769", scorer: "Vitor Roque", kind: "penalty", minute: "50'" },
    { clubCode: "1769", scorer: "Mauricio", minute: "55'" },
    { clubCode: "1769", scorer: "Lopez", minute: "89'" },
    { clubCode: "1780", scorer: "Facundo", minute: "90+3'" },
  ],
  "554978": [
    { clubCode: "4364", scorer: "Carlos", minute: "35'" },
    { clubCode: "6685", scorer: "Barreal", minute: "67'" },
  ],
  "554979": [
    { clubCode: "1777", scorer: "Alejo", minute: "67'" },
    { clubCode: "1777", scorer: "Jean Lucas", minute: "90+6'" },
  ],
  "554980": [
    { clubCode: "1768", scorer: "Leozinho", minute: "34'" },
    { clubCode: "1765", scorer: "Hulk", kind: "freekick", minute: "37'" },
    { clubCode: "1768", scorer: "Gaston Benavidez", minute: "48'" },
    { clubCode: "1765", scorer: "Canobbio", minute: "64'" },
    { clubCode: "1765", scorer: "Ignacio", minute: "78'" },
    { clubCode: "1768", scorer: "Kevin Viveros", kind: "penalty", minute: "90+5'" },
  ],
  "554981": [
    { clubCode: "1766", scorer: "Thiago Borbas", minute: "25'" },
    { clubCode: "1766", scorer: "Reinier", minute: "63'" },
    { clubCode: "1782", scorer: "Erick", minute: "87'" },
  ],
  "554988": [
    { clubCode: "1776", scorer: "Luciano", kind: "penalty", minute: "13'" },
    { clubCode: "1776", scorer: "Gustavo Santana", minute: "45+4'" },
    { clubCode: "4286", scorer: "Fernando", minute: "90'" },
  ],
  "554989": [
    { clubCode: "1780", scorer: "Tche Tche", minute: "33'" },
    { clubCode: "1780", scorer: "Lucas", minute: "54'" },
    { clubCode: "1780", scorer: "David", minute: "90+4'" },
    { clubCode: "1771", scorer: "Felipe de Morais", minute: "90+1'" },
  ],
};
