import type { Goal } from "@/src/types";

/**
 * GENERATED by scripts/sync-goals.ts — but safe to hand-edit.
 *
 * Who scored, per match. **No football-data tier this app can reach carries
 * goal events** — verified against a live Série A match and a live Premier
 * League one, both free, both answering with no `goals` key at all — so this
 * comes from CBF's own match endpoint, read on a workstation and never by the
 * running app. See `docs/data-sources.md`.
 *
 * Keyed by **our** match id, for the reason `broadcasts.ts` is: CBF's ids are
 * its own.
 *
 * **Every entry here has been reconciled against its own scoreline** — the
 * goals attributed to each club add up to that club's score, checked both
 * against CBF's reported score and against ours — and the sync refuses to write
 * one that does not. A missing match means "not synced, or did not reconcile",
 * never "goalless": a real 0-0 is deliberately absent rather than an empty
 * array, since the two would be indistinguishable here.
 *
 * **Coverage is one match.** CBF throttles at the socket rather than with a
 * status code — see `scripts/cbf-api.ts` — and blocked this workstation part
 * way through the first season-wide run, so the rest is a `npm run sync-goals`
 * away rather than a code change. This entry was not typed by hand: it is the
 * output of `goalsFromRegistros` over CBF's real payload for `id_jogo=832123`,
 * which reconciles against both scorelines.
 */
export const GOALS: Record<string, Goal[]> = {
  "554977": [
    { clubCode: "1769", scorer: "Lopez" },
    { clubCode: "1769", scorer: "Vitor Roque", kind: "penalty" },
    { clubCode: "1769", scorer: "Mauricio" },
    { clubCode: "1769", scorer: "Lopez" },
    { clubCode: "1780", scorer: "Facundo" },
  ],
};
