import type { Venue } from "@/src/types";

/**
 * GENERATED by scripts/sync-broadcasts.ts — but safe to hand-edit.
 *
 * Stadium, city and state per match, keyed by **our** match id. The data
 * provider carries no venue field at all, so this comes from CBF's Onde
 * Assistir feed, which reports it as "Stadium - City - UF".
 *
 * Values are verbatim: CBF's casing and accents drift (`ARENA MRV`,
 * `Sao Paulo` without the tilde) and correcting them would mean guessing at
 * proper names.
 *
 * Last synced 2026-08-24.
 */
export const VENUES: Record<string, Venue> = {
  "554970": { stadium: "Nilton Santos", city: "Rio de Janeiro", state: "RJ" },
  "554971": { stadium: "Cícero de Souza Marques", city: "Braganca Paulista", state: "SP" },
  "554972": { stadium: "Arena Condá", city: "Chapeco", state: "SC" },
  "554973": { stadium: "Couto Pereira", city: "Curitiba", state: "PR" },
  "554974": { stadium: "Mineirão", city: "Belo Horizonte", state: "MG" },
  "554975": { stadium: "Maracanã", city: "Rio de Janeiro", state: "RJ" },
  "554976": { stadium: "Beira-Rio", city: "Porto Alegre", state: "RS" },
  "554977": { stadium: "Nubank Parque", city: "Sao Paulo", state: "SP" },
  "554978": { stadium: "Vila Belmiro", city: "Santos", state: "SP" },
  "554979": { stadium: "Manoel Barradas", city: "Salvador", state: "BA" },
  "554980": { stadium: "Arena da Baixada", city: "Curitiba", state: "PR" },
  "554981": { stadium: "ARENA MRV", city: "Belo Horizonte", state: "MG" },
  "554982": { stadium: "Arena Fonte Nova", city: "Salvador", state: "BA" },
  "554983": { stadium: "Neo Química Arena", city: "Sao Paulo", state: "SP" },
  "554984": { stadium: "Maracanã", city: "Rio de Janeiro", state: "RJ" },
  "554985": { stadium: "Arena do Grêmio", city: "Porto Alegre", state: "RS" },
  "554986": { stadium: "José Maria de Campos Maia", city: "Mirassol", state: "SP" },
  "554987": { stadium: "Mangueirão", city: "Belem", state: "PA" },
  "554988": { stadium: "Morumbi", city: "Sao Paulo", state: "SP" },
  "554989": { stadium: "São Januário", city: "Rio de Janeiro", state: "RJ" },
  "554990": { stadium: "Nilton Santos", city: "Rio de Janeiro", state: "RJ" },
  "554991": { stadium: "Cícero de Souza Marques", city: "Braganca Paulista", state: "SP" },
  "554992": { stadium: "Neo Química Arena", city: "Sao Paulo", state: "SP" },
  "554993": { stadium: "Couto Pereira", city: "Curitiba", state: "PR" },
  "554994": { stadium: "Mineirão", city: "Belo Horizonte", state: "MG" },
  "554995": { stadium: "Maracanã", city: "Rio de Janeiro", state: "RJ" },
  "554996": { stadium: "Beira-Rio", city: "Porto Alegre", state: "RS" },
  "554997": { stadium: "Mangueirão", city: "Belem", state: "PA" },
  "554998": { stadium: "Morumbi", city: "Sao Paulo", state: "SP" },
  "554999": { stadium: "Manoel Barradas", city: "Salvador", state: "BA" },
};
